gentics/mesh

core/src/main/java/com/gentics/mesh/core/verticle/admin/RestInfoEndpoint.java
rest-model/src/main/java/com/gentics/mesh/http/HttpConstants.java

Change Content-Type of /api/v1/raml to application/x-yaml

---

common/src/main/java/com/gentics/mesh/core/data/node/field/FieldTransformator.java
core/src/main/java/com/gentics/mesh/core/data/container/impl/AbstractGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/GraphFieldTypes.java
core/src/main/java/com/gentics/mesh/core/data/node/field/impl/HtmlGraphFieldImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/field/impl/StringGraphFieldImpl.java

Change parentNode parameter to Supplier of the parent node

---

CHANGELOG.pending.adoc
common/src/main/java/com/gentics/mesh/core/data/node/field/BinaryGraphField.java
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
common/src/main/java/com/gentics/mesh/core/image/spi/ImageManipulator.java
common/src/main/java/com/gentics/mesh/util/PropReadFileStream.java
common/src/main/java/com/gentics/mesh/util/RxUtil.java
core/src/main/java/com/gentics/mesh/core/data/node/field/impl/BinaryGraphFieldImpl.java
core/src/main/java/com/gentics/mesh/core/verticle/migration/AbstractMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/verticle/node/BinaryFieldHandler.java
core/src/main/java/com/gentics/mesh/core/verticle/node/BinaryFieldResponseHandler.java
core/src/test/java/com/gentics/mesh/core/schema/field/BinaryFieldMigrationTest.java
services/image-imgscalr/src/main/java/com/gentics/mesh/image/ImgscalrImageManipulator.java
services/image-imgscalr/src/test/java/com/gentics/mesh/image/ImgscalrImageManipulatorTest.java

Optimize binary download

---

common/src/main/java/com/gentics/mesh/core/data/page/impl/DynamicStreamPageImpl.java
common/src/main/java/com/gentics/mesh/core/data/schema/SchemaContainerVersion.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/SchemaContainerVersionImpl.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
core/src/test/resources/graphql/release-query
core/src/test/resources/graphql/schema-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/AbstractTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/ReleaseTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/RoleTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/SchemaTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/TagFamilyTypeProvider.java

This lists all nodes of that schema in the current release.
Fixes #157

GraphQL: Add nodes field to schema type

---

core/src/main/java/com/gentics/mesh/core/data/container/impl/MicroschemaContainerVersionImpl.java

When migrating microschema fields a call to dedup while traversing the nodes caused the whole vertex frame for each field to be stored in a set. When migrating a large number of fields this could cause an OOM-Exception. With this fix the call to dedup will now only store the Id of the Vertex.

Fixed #212: reduce memory load during migrations.

---

CHANGELOG.adoc
core/src/test/resources/graphql/schema-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/SchemaTypeProvider.java

Make schema fields available in GraphQL

Dev 0.15.x schema fields

---

core/src/test/java/com/gentics/mesh/core/utilities/AbstractValidateSchemaTest.java
core/src/test/java/com/gentics/mesh/core/utilities/ValidateMicroSchemaTest.java
core/src/test/java/com/gentics/mesh/core/utilities/ValidateSchemaTest.java
core/src/test/java/com/gentics/mesh/test/context/AbstractMeshTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHttpMethods.java

Tests for Issues #277 and #278

Create Tests for (Micro-)Schema Validation

---

CHANGELOG.adoc
core/src/test/java/com/gentics/mesh/core/graphql/AbstractGraphQLSearchEndpointTest.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLNodeLanguageSearchEnpointTest.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLSearchEndpointTest.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLUserScrollSearchEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/MeshTestContext.java
core/src/test/resources/graphql/node-elasticsearch-language-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java

Fix language parameter is ignored in GraphQL response

---

core/src/test/java/com/gentics/mesh/core/field/micronode/MicronodeListFieldEndpointTest.java
core/src/test/java/com/gentics/mesh/core/field/number/NumberFieldListEndpointTest.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/NodeUpdateRequest.java

Test order of micronode lists 

---

core/src/main/java/com/gentics/mesh/core/endpoint/group/GroupEndpoint.java
core/src/main/java/com/gentics/mesh/search/SearchEndpointImpl.java

I looked through the api docs.
The paging query parameters were missing for:
- search
- group/:groupUuid/users

add query params to api docs

---

CHANGELOG.adoc
core/src/test/java/com/gentics/mesh/plugin/PluginConfigTest.java
plugin-api/src/main/java/com/gentics/mesh/plugin/AbstractPluginVerticle.java
plugin-api/src/main/java/com/gentics/mesh/plugin/PluginConfigUtil.java

to override parts of config.yml

Allow local plugin config file (config.local.yml) 

---

CHANGELOG.adoc
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java

Fix node graph field container error messsage

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/Branch.java
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/BranchImpl.java
core/src/main/java/com/gentics/mesh/core/data/job/impl/NodeMigrationJobImpl.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/FieldTypeChangeImpl.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/UpdateFieldChangeImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/branch/BranchCrudHandler.java
core/src/main/java/com/gentics/mesh/util/PentaFunction.java
core/src/test/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/MigrationFailureRecoveryTest.java
core/src/test/java/com/gentics/mesh/core/schema/NodeMigrationFailureRecoveryTest.java
core/src/test/java/com/gentics/mesh/core/schema/SchemaChangesEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/AbstractMeshTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandler.java
rest-model/src/main/java/com/gentics/mesh/core/rest/microschema/impl/MicroschemaResponse.java
test-common/src/main/java/com/gentics/mesh/test/util/TestUtils.java

Fix /migrateSchemas endpoint

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/root/BranchRoot.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/BranchRootImpl.java
core/src/test/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
core/src/test/java/com/gentics/mesh/core/node/NodeChildrenEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/MigrationFailureRecoveryTest.java
core/src/test/java/com/gentics/mesh/search/MultipleActionsTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelperMethods.java
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/impl/SchemaResponse.java
test-common/src/main/java/com/gentics/mesh/test/util/MeshAssert.java
test-common/src/main/java/com/gentics/mesh/test/util/TestUtils.java

Migrate nodes to newest schema when creating new branch

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/User.java
common/src/main/java/com/gentics/mesh/core/data/page/impl/DynamicTransformablePageImpl.java
core/src/main/java/com/gentics/mesh/context/impl/NodeMigrationActionContextImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/consistency/check/UserCheck.java
core/src/test/java/com/gentics/mesh/core/user/UserEndpointTest.java
rest-model/src/main/java/com/gentics/mesh/core/rest/user/UserResponse.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/UserTypeProvider.java

Dev user roles

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/User.java
core/src/main/java/com/gentics/mesh/context/impl/NodeMigrationActionContextImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/test/java/com/gentics/mesh/core/user/UserEndpointTest.java
core/src/test/java/com/gentics/mesh/core/user/UserTest.java
doc/src/main/docs/cookbook/index.asciidoc
rest-model/src/main/java/com/gentics/mesh/core/rest/user/UserResponse.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/UserTypeProvider.java

* Remove roles from REST user response
* Add `rolesHash` to REST user response and GraphQL user fields

Add user roles hash to user responses

---

pom.xml

Bump spring security version

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/job/impl/JobImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/JobHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
core/src/test/java/com/gentics/mesh/core/job/JobEndpointTest.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/JobClientMethods.java

Add jobs/:uuid/process endpoint

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryFieldHandler.java
core/src/test/java/com/gentics/mesh/core/node/NodeImageResizeEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelperMethods.java

Fix image transform webroot

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/MeshVertex.java
common/src/main/java/com/gentics/mesh/core/data/node/Node.java
common/src/main/java/com/gentics/mesh/core/data/relationship/GraphPermission.java
core/src/main/java/com/gentics/mesh/core/data/impl/RoleImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/test/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
core/src/test/java/com/gentics/mesh/core/group/GroupEndpointTest.java
core/src/test/java/com/gentics/mesh/core/node/NodeEndpointTest.java
core/src/test/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
core/src/test/java/com/gentics/mesh/core/role/RoleEndpointPermissionsTest.java
core/src/test/java/com/gentics/mesh/core/role/RoleEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/MicroschemaEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/SchemaEndpointTest.java
core/src/test/java/com/gentics/mesh/core/tag/TagEndpointTest.java
core/src/test/java/com/gentics/mesh/core/tagfamily/TagFamilyEndpointTest.java
core/src/test/java/com/gentics/mesh/core/user/UserEndpointTest.java
core/src/test/java/com/gentics/mesh/test/definition/CrudEndpointTestCases.java
rest-model/src/main/java/com/gentics/mesh/core/rest/common/Permission.java
rest-model/src/main/java/com/gentics/mesh/core/rest/common/PermissionInfo.java
test-common/src/main/java/com/gentics/mesh/assertj/impl/PermissionInfoAssert.java

Don't return published and readPublished permissions for elements other than nodes

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/schema/impl/AddFieldChangeImpl.java
core/src/test/java/com/gentics/mesh/core/schema/MicroschemaDiffEndpointTest.java

Fix microschema diff endpoint

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryFieldResponseHandler.java
core/src/main/java/com/gentics/mesh/util/EncodeUtil.java
core/src/test/java/com/gentics/mesh/core/node/NodeEndpointBinaryFieldTest.java

Improves PR #730 with tests, changelog.

Fix content disposition header

---

CHANGELOG.adoc
rest-model/src/main/java/com/gentics/mesh/core/rest/branch/BranchResponse.java
test-common/src/main/java/com/gentics/mesh/assertj/impl/BranchResponseAssert.java

Change migrated field to from boolean to Boolean

---

CHANGELOG.adoc
Jenkinsfile.split
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
core/src/test/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

Image manipulation returns same image with changed parameters

---

common/pom.xml
common/src/test/java/com/gentics/mesh/OptionsLoaderTest.java
elasticsearch/pom.xml
elasticsearch/src/test/java/com/gentics/mesh/search/ElasticsearchProcessManagerTest.java
pom.xml

use junit test Rule for setting env variables

---

rest-model/src/main/java/com/gentics/mesh/core/rest/common/AbstractNameUuidReference.java
rest-model/src/main/java/com/gentics/mesh/core/rest/common/AbstractResponse.java

Adding equals & hashcode methods to Rest models to help compare lists.

Equals method for Rest Models

---

CHANGELOG.adoc
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/PluginApiTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java

Don't add pluginApi if no plugins have been registered

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java

Make index sync at startup non blocking

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/Project.java
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacer.java
core/src/main/java/com/gentics/mesh/core/data/impl/ProjectImpl.java
core/src/test/java/com/gentics/mesh/linkrenderer/BranchLinkRendererTest.java
doc/src/main/docs/features.asciidoc

Resolves https://github.com/gentics/mesh-incubator/issues/38

Add branches to mesh links

---

api/src/main/java/com/gentics/mesh/etc/config/AuthenticationOptions.java
api/src/main/java/com/gentics/mesh/etc/config/ClusterOptions.java
api/src/main/java/com/gentics/mesh/etc/config/ContentConfig.java
api/src/main/java/com/gentics/mesh/etc/config/DebugInfoOptions.java
api/src/main/java/com/gentics/mesh/etc/config/GraphStorageOptions.java
api/src/main/java/com/gentics/mesh/etc/config/HttpServerConfig.java
api/src/main/java/com/gentics/mesh/etc/config/ImageManipulatorOptions.java
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
api/src/main/java/com/gentics/mesh/etc/config/MonitoringConfig.java
api/src/main/java/com/gentics/mesh/etc/config/search/ElasticSearchOptions.java

Cleaned up Option Objects

---

CHANGELOG.adoc
bom/pom.xml
core/src/main/java/com/gentics/mesh/core/binary/DocumentTikaParser.java
core/src/main/java/com/gentics/mesh/core/binary/impl/TikaBinaryProcessor.java
core/src/test/java/com/gentics/mesh/core/binary/impl/TikaBinaryProcessorTest.java
services/image-imgscalr/pom.xml

See also https://issues.apache.org/jira/browse/TIKA-2109

Use experimental docx and pptx parser

---

CHANGELOG.adoc
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
core/src/test/resources/graphql/user-node-reference
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/UserTypeProvider.java

Fix fetching node refernence from user in GraphQL

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/rest/InternalEndpoint.java
common/src/main/java/com/gentics/mesh/rest/impl/InternalEndpointRouteImpl.java

Reduces calls to generate JsonSchema and also uses static class to provide examples.

REST API Startup Enhancements

---

CHANGELOG.adoc
api/pom.xml
api/src/main/java/com/gentics/mesh/util/UUIDUtil.java
api/src/main/java/com/gentics/mesh/util/VersionNumber.java
bom/pom.xml
plugin-api/src/main/java/com/gentics/mesh/plugin/RestPlugin.java
pom.xml

Bump deps and fix javadoc

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
core/src/test/java/com/gentics/mesh/core/schema/MicronodeMigrationAllFieldsTest.java

Fixed a bug that caused errors during microschema migrations in certain situations.

Fix bug in microschema migration

---

CHANGELOG.adoc
bom/pom.xml
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java

Bump OrientDB version to 3.0.29

Bump OrientDB version

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/verticle/handler/HandlerUtilities.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/ShutdownHandler.java

Add shutdown endpoint

---

api/src/main/java/com/gentics/mesh/etc/config/ClusterOptions.java
api/src/main/java/com/gentics/mesh/etc/config/cluster/CoordiationTopology.java
api/src/main/java/com/gentics/mesh/etc/config/cluster/CoordinationTopology.java
common/src/main/java/com/gentics/mesh/graphdb/spi/Database.java
databases/neo4j/src/main/java/com/gentics/mesh/neo4j/Neo4jDatabase.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/MasterElector.java
doc/src/main/docs/clustering.asciidoc

Add Master/Replica failover support

---

CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/GraphStorageOptions.java
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
common/src/main/java/com/gentics/mesh/core/verticle/handler/WriteLockImpl.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/RevisionHashFileGenerator.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/TxCleanupTask.java
databases/orientdb/src/main/java/com/syncleus/ferma/ext/orientdb3/OrientDBTx.java
databases/orientdb/src/test/java/com/gentics/mesh/graphdb/orientdb/AbstractOrientDBTest.java
databases/orientdb/src/test/java/com/gentics/mesh/graphdb/orientdb/changelog/ChangelogSystemTest.java
doc/src/main/java/com/gentics/mesh/generator/DatabaseRevisionTableGenerator.java
server/src/main/java/com/gentics/mesh/server/cluster/ClusterServer.java

* Adds tx cleanup task
* Adds timeout setting for existing local write lock

Tx Cleanup Task / Write Lock Timeout

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/verticle/handler/WriteLock.java
common/src/main/java/com/gentics/mesh/core/verticle/handler/WriteLockImpl.java
common/src/main/java/com/gentics/mesh/metric/SimpleMetric.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/TxCleanupTask.java
databases/orientdb/src/main/java/com/syncleus/ferma/ext/orientdb3/OrientDBTx.java
doc/src/main/docs/monitoring.asciidoc

Adds monitoring metrics for the new locks.

Hotfix 1.4.x cluster monitoring

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/generic/PermissionProperties.java
core/src/test/java/com/gentics/mesh/search/RoleDeleteSyncTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelper.java
rest-model/src/main/java/com/gentics/mesh/core/rest/role/RolePermissionRequest.java

Fix NPE in ES sync after role deletion

---

CHANGELOG.adoc
services/jwt-auth/src/main/java/com/gentics/mesh/auth/MeshOAuth2ServiceImpl.java

Adds missing write lock to Tx in OAuth handler

Add write lock for OAuth/external JWT handling

---

CHANGELOG.adoc
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshRequest.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java

Close response body on `blockingAwait()`

---

common/src/main/java/com/gentics/mesh/core/data/NodeGraphFieldContainer.java
core/src/test/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
core/src/test/java/com/gentics/mesh/search/LanguageOverrideSearchTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelper.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/project/ProjectDeleteEventHandler.java

Language specific indices were not deleted

Drop all node indices when project is deleted

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/admin/plugin/PluginHandler.java
core/src/main/java/com/gentics/mesh/plugin/manager/MeshPluginManagerImpl.java
core/src/main/java/com/gentics/mesh/plugin/registry/DelegatingPluginRegistryImpl.java
core/src/test/java/com/gentics/mesh/core/admin/AdminPluginEndpointTest.java

* Fixes NPE in undeployment code
* Adds more logging on cluster lock handling
* Re-order lock and quorum check during plugin deployments

Add fix for plugin undeploy NPE

---

doc/src/main/docs/administration-guide.asciidoc

Wording in administration guides needs to be clearer on the behaviour of mesh.yml and environment variables

use clear wording on use of environment variables

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/User.java
core/src/main/java/com/gentics/mesh/context/impl/NodeMigrationActionContextImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/test/resources/graphql/anonymous-perm-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java

Fix loading draft version via GraphQL without permission

---

verticles/admin-gui/src/main/resources/meshui-templates/mesh-ui2-config.hbs

Changed Mesh UI 2 to contain the Hungarian language in the configuration.

Add Hungarian language to Mesh UI 2 configuration

---

databases/orientdb/src/test/java/com/gentics/mesh/graphdb/orientdb/graph/Person.java

Extract some User methods to UserRoot

---

test-common/src/test/java/com/gentics/mesh/test/util/UnixUtilsTest.java

add os check before unix utils tests

---

.gitignore
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java
core/src/test/java/com/gentics/mesh/core/monitoring/MonitoringServerEndpointTest.java
core/src/test/java/com/gentics/mesh/plugin/FailingShutdownPlugin.java

(cherry picked from commit 22e16655693fb25472c8be516cba65573cf3f3d3)

Add check for failed plugin deployments

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/webroot/WebRootHandler.java

Remove webroot write lock

---

.gitignore
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java

Log readiness check failures to warn instead of debug

---

doc/src/main/docs/elasticsearch.asciidoc

I just updated the documentation

update documentation for search by micronode field values

---

LTS-CHANGELOG.adoc
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java

Adds NPE checks and needed debug output for oauth mapping code.

Add more null checks and debug output for mapping and jwt code. Fixes #1138

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/PermissionCacheImpl.java
core/src/main/java/com/gentics/mesh/cache/ProjectBranchNameCacheImpl.java
core/src/main/java/com/gentics/mesh/cache/ProjectNameCacheImpl.java
core/src/main/java/com/gentics/mesh/cache/WebrootPathCacheImpl.java

Invoke cache clear on cluster topology events

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/parameter/ParameterProviderContext.java
common/src/main/java/com/gentics/mesh/parameter/impl/BackupParametersImpl.java
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
core/src/test/java/com/gentics/mesh/core/admin/AdminEndpointBackupLocalTest.java
rest-client/src/main/java/com/gentics/mesh/parameter/client/BackupParametersImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/AdminClientMethods.java
rest-model/src/main/java/com/gentics/mesh/parameter/BackupParameters.java

Add consistency check query parameter to backup endpoint

---

LTS-CHANGELOG.adoc
test-common/src/main/java/com/gentics/mesh/test/docker/MeshContainer.java
test-common/src/test/java/com/gentics/mesh/test/docker/MeshContainerTest.java

Update container path handling

---

LTS-CHANGELOG.adoc
core/src/main/java/org/apache/pdfbox/pdmodel/PDDocument.java
core/src/test/java/com/gentics/mesh/core/binary/DocumentTikaParserTest.java
core/src/test/java/com/gentics/mesh/core/binary/impl/FileUploadClientTest.java
core/src/test/java/com/gentics/mesh/core/binary/impl/TikaBinaryProcessorTest.java

Add PDF Parser Patch

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/index/entry/AbstractIndexHandler.java

Fix potential NPE during index sync for missing graph elements

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/node/field/impl/BinaryGraphFieldImpl.java

Fix binary metadata processing when brackets were in the metadata key

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/GraphQLOptions.java
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
common/src/main/java/com/gentics/mesh/metric/SimpleMetric.java
doc/src/main/docs/administration-guide.asciidoc
doc/src/main/docs/graphql.asciidoc
doc/src/main/docs/monitoring.asciidoc
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java

Add slow query log for GraphQL

---

LTS-CHANGELOG.adoc
bom/pom.xml

Update OrientDB version to v3.1.10.

Bump OrientDB version to v3.1.10

---

README.md
pom.xml

Remove Johannes Schüth from core developers

---

core/src/main/java/com/gentics/mesh/core/data/container/impl/AbstractGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/field/impl/S3BinaryGraphFieldImpl.java
core/src/main/java/com/gentics/mesh/core/data/s3binary/impl/S3BinariesImpl.java
core/src/main/java/com/gentics/mesh/core/data/s3binary/impl/S3BinaryImpl.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/AddFieldChangeImpl.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/FieldTypeChangeImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/s3binary/S3HibBinary.java
mdm/api/src/main/java/com/gentics/mesh/core/data/s3binary/S3HibBinaryField.java
mdm/common/src/main/java/com/gentics/mesh/FieldUtil.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/GraphFieldContainer.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/node/field/S3BinaryGraphField.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/s3binary/S3Binaries.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/s3binary/S3Binary.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/util/HibClassConverter.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/db/Tx.java
rest-model/src/main/java/com/gentics/mesh/core/rest/common/FieldTypes.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/FieldMap.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/FieldMapImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/S3BinaryField.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/impl/S3BinaryFieldImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/s3binary/S3BinaryMetadata.java
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/S3BinaryExtractOptions.java
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/S3BinaryFieldSchema.java
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/impl/S3BinaryFieldSchemaImpl.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/FieldFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Code for the creation of the S3 binary field. This branch covers only the S3 binary field, without tests and without extended functionality that will be covered from future tickets (This is the ticket board: https://jira.gentics.com/secure/RapidBoard.jspa?rapidView=103&projectKey=MS3&view=detail)

feature/MS3-5 Add S3 binary field

---

LTS-CHANGELOG.adoc
bom/pom.xml
core/src/main/java/com/gentics/mesh/core/binary/impl/TikaBinaryProcessor.java
core/src/test/java/com/gentics/mesh/core/field/binary/BinaryFieldUploadEndpointTest.java

Update Tika Parser to 1.26

---

core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/s3binary/impl/S3BinaryImpl.java
mdm/common/src/main/java/com/gentics/mesh/dagger/BaseMeshComponent.java
mdm/common/src/main/java/com/gentics/mesh/storage/S3BinaryStorage.java
services/aws-s3-storage/src/main/java/com/gentics/mesh/storage/s3/S3BinaryStorageImpl.java

Delete S3 binary when node gets deleted.

MS3-12 Delete S3 Binary

---

LTS-CHANGELOG.adoc
bom/pom.xml
core/src/main/java/com/gentics/mesh/core/endpoint/webrootfield/WebRootFieldHandler.java
core/src/main/java/com/gentics/mesh/dagger/module/MicrometerModule.java

Update OrientDB to 3.1.11

---

verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Hotfix 1.6.x sup 11537

---

core/src/main/java/com/gentics/mesh/core/endpoint/node/S3BinaryUploadHandlerImpl.java

SUP-11538/fix for the update issue in the S3 field

---

LTS-CHANGELOG.adoc
changelog-system/src/main/java/com/gentics/mesh/changelog/ChangelogSystem.java
common/src/main/java/com/gentics/mesh/cli/BootstrapInitializer.java
common/src/main/java/com/gentics/mesh/core/data/changelog/HighLevelChange.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/HighLevelChangelogSystem.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/ExtractPlainText.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/PrepareBucketableElements.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/RestructureWebrootIndex.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/SetAdminUserFlag.java
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java

if missing high level changes allow this

Make it possible to do a rolling update of Mesh in a cluster,

---

core/src/main/java/com/gentics/mesh/core/project/maintenance/ProjectVersionPurgeHandlerImpl.java

When deleting old versions of nodes, files were not deleted from the disk. It seems that the reason is that there is no call to BulkActionContext.process after purging nodes.
Add BulkActionContext to purgeVersions method, push it to purgeVersion method, and finally call force process from BulkActionContext.

Add BulkActionContext.process(force) to purge nodes process

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/MeshVertex.java
common/src/main/java/com/gentics/mesh/core/data/Role.java
core/src/main/java/com/gentics/mesh/context/impl/NodeMigrationActionContextImpl.java
core/src/main/java/com/gentics/mesh/core/data/generic/MeshVertexImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/GroupImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/ProjectImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/RoleImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/TagFamilyImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/AbstractRootVertex.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/NodeRootImpl.java
core/src/test/java/com/gentics/mesh/core/role/RoleEndpointPermissionsTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandler.java

Fix "empty" permission update to not publish events

Fix full sync to not remove language specific indices

---

core/src/main/java/com/gentics/mesh/core/actions/impl/MicroschemaDAOActionsImpl.java
core/src/main/java/com/gentics/mesh/core/data/container/impl/MicroschemaContainerVersionImpl.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/ProjectMicroschemaContainerRootImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/HibLanguage.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/LanguageDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/MicroschemaDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ProjectDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/schema/HibMicroschemaVersion.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/Language.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/LanguageDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/MicroschemaDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/ProjectDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/SchemaDaoWrapperImpl.java

Implemented default methods in the following DAO interfaces:
* **MicroschemaDao**
* **HibMicroschemaVersion**
* **LanguageDao**
Added **onMicroschemaAssignEvent** to **ProjectDao**
Delegated **transformToRestSync** to **MicroschemaDao** in **MicroschemaDAOActionsImpl**
Implemented **public void addMicroschema(HibMicroschema microschema)** in **MicroschemaDaoWrapperImpl**
Implemented **onMicroschemaAssignEvent** in **ProjectDaoWrapperImpl**

CL-654 extract common function to daos

---

LTS-CHANGELOG.adoc
bom/pom.xml

Update to OrientDB version 3.1.14

Update to orientdb 3.1.14

---

tests/tests-core/src/main/java/com/gentics/mesh/test/TestDataProvider.java

Small changes to make the test setup work in an enterprise test context

Ignore permissions for mocked entities

---

SECURITY.md

We already have a vulnerability disclosure policy in our website but it's common practice to have this outlined also in a separate markdown file
See #1290

Create SECURITY.md as per github guidelines

---

LTS-CHANGELOG.adoc
bom/pom.xml

Dependencies updated. CI looks good

Dependency update

---

tests/tests-core/src/main/java/com/gentics/mesh/core/group/GroupRolesEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/group/GroupUserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserTest.java

Mdm development content fix group assignment tests

---

mdm/api/src/main/java/com/gentics/mesh/core/data/node/HibNode.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/node/Node.java
tests/tests-core/src/main/java/com/gentics/mesh/core/group/GroupRolesEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/group/GroupUserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/role/RoleTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserTest.java

Fix a couple of tests that were failing for mdm and node permissions

Mdm development content fix role group

---

.gitignore
core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingProjectDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRootDao.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/VersionPurgeJobProcessor.java
rest-model/src/main/java/com/gentics/mesh/core/rest/branch/BranchResponse.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectTest.java

Add a few fixes to make branch tests work on mdm

branch fixes

---

.gitignore
core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingProjectDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRootDao.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/VersionPurgeJobProcessor.java
rest-model/src/main/java/com/gentics/mesh/core/rest/branch/BranchResponse.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectTest.java

This reverts commit 5c08e13bcd93604255b0f288c13741097752c445.

Revert "branch fixes (#1305)"

---

.gitignore
core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingProjectDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRootDao.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/VersionPurgeJobProcessor.java
rest-model/src/main/java/com/gentics/mesh/core/rest/branch/BranchResponse.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectTest.java

Contains some refactoring and text fixes related to mdm branch and project implementations

Mdm branch test fixes

---

core/src/main/java/com/gentics/mesh/core/endpoint/project/ProjectCrudHandler.java

The nested transaction is not necessary and make problems due to transaction isolation.

Remove nested transaction

---

mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java

Fix possible NPE when deleting a project

---

core/src/main/java/com/gentics/mesh/core/migration/impl/MicronodeMigrationImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/changelog/ChangeMarker.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ChangelogDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/MicroschemaMigrationTest.java

Remove unnecessary nested transaction and fix migration of

---

core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/branch/HibBranch.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/BranchImpl.java
tests/common/src/main/java/com/gentics/mesh/assertj/impl/BranchAssert.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/BaseHelper.java

branches can have many next branches

---

mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
tests/common/src/main/java/com/gentics/mesh/assertj/impl/NodeGraphFieldContainerAssert.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointETagTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeTagEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeTakeOfflineEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/TestDataProvider.java

Adaptation of test in package com.gentics.mesh.core.node to work with mdm version

Mdm node test fixes

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/root/RootVertex.java
common/src/main/java/com/gentics/mesh/parameter/ParameterProviderContext.java
common/src/main/java/com/gentics/mesh/parameter/impl/JobParametersImpl.java
core/src/main/java/com/gentics/mesh/core/data/job/impl/JobRootImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/JobHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
core/src/test/java/com/gentics/mesh/core/job/JobEndpointTest.java
rest-client/src/main/java/com/gentics/mesh/parameter/client/JobParametersImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/JobClientMethods.java
rest-model/src/main/java/com/gentics/mesh/parameter/JobParameters.java
rest-model/src/main/java/com/gentics/mesh/parameter/ParameterProvider.java

The endpoint for getting jobs returns the jobs in an undefined order and also returned COMPLETED jobs, which makes finding the right information cumbersome.
Therefore some filters have been added.

Hotfix 1.6.x sup 12433

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/JobHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/JobDao.java
mdm/api/src/main/java/com/gentics/mesh/parameter/ParameterProviderContext.java
mdm/api/src/main/java/com/gentics/mesh/parameter/impl/JobParametersImpl.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/root/RootVertex.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/JobDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/job/impl/JobRootImpl.java
rest-client/src/main/java/com/gentics/mesh/parameter/client/JobParametersImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/JobClientMethods.java
rest-model/src/main/java/com/gentics/mesh/parameter/JobParameters.java
rest-model/src/main/java/com/gentics/mesh/parameter/ParameterProvider.java
tests/tests-core/src/main/java/com/gentics/mesh/core/job/JobEndpointTest.java

Port SUP-12433 to dev

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java

Create temporary indices with installation prefix

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java

Port SUP-12514 to dev

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
bom/pom.xml

Port SUP-12971 to dev

---

tests/context-api/src/main/java/com/gentics/mesh/test/MeshInstanceProvider.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Fast unit test db cleanup

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManagerImpl.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/TopologyEventBridge.java

Port SUP-13202 to dev

---

LTS-CHANGELOG.adoc
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/TopologyEventBridge.java

Wait for topology lock to be raised before applying changelog and

---

elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandlerImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/search/index/MicronodeIndexSyncTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/EventHelper.java
tests/tests-core/src/main/resources/elasticsearch/custom/languageOverride.json

Fix resync of node index with language code and microschema hash

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
pom.xml

Update Mesh UI to version 1.3.2.

UI -> 1.3.2

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/cli/OrientDBBootstrapInitializerImpl.java

Port SUP-13247 to 1.8.x

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/ClientHelper.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/EventHelper.java

Port of SUP-13248

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
core/src/main/java/com/gentics/mesh/cache/ProjectNameCacheImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
distributed/src/main/java/com/gentics/mesh/distributed/DistributedEventManager.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/endpoint/admin/OrientDBAdminHandler.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/AdminClientMethods.java
rest-model/src/main/java/com/gentics/mesh/core/rest/MeshEvent.java
tests/tests-core/src/main/java/com/gentics/mesh/core/admin/AdminEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java

Port SUP-13340 to 1.8.x

---

LTS-CHANGELOG.adoc
bom/pom.xml

Update OrientDB Version

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
api/src/main/java/com/gentics/mesh/etc/config/VertxEventBusOptions.java
api/src/main/java/com/gentics/mesh/etc/config/VertxOptions.java
common/src/main/java/com/gentics/mesh/dagger/MeshComponent.java
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
core/src/main/java/com/gentics/mesh/dagger/module/CommonBindModule.java
core/src/main/java/com/gentics/mesh/event/EventBusLivenessManagerImpl.java
mdm/common/src/main/java/com/gentics/mesh/monitor/liveness/EventBusLivenessManager.java
rest-model/src/main/java/com/gentics/mesh/core/rest/MeshEvent.java

Port of SUP-13379

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/PermissionCacheImpl.java
mdm/api/src/main/java/com/gentics/mesh/cache/PermissionCache.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingGroupDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRoleDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/GroupDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/RoleDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/UserDaoWrapperImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/perm/PermissionCacheTest.java

Improve permission cache to also store not granted permissions and to

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/schema/impl/SchemaContainerVersionImpl.java
core/src/test/java/com/gentics/mesh/core/schema/SchemaEndpointTest.java

Fix possible NPE when getting the microschema version hash

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/DiskQuotaOptions.java
doc/src/main/docs/administration-guide.asciidoc

Change defaults for disk quota checker

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
server/Dockerfile

Port of SUP-12908

---

demo/src/main/java/com/gentics/mesh/demo/DemoDumpGenerator.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractMeshTest.java

Fix for running latest in-memory OrientDB

---

.jenkins/run-splits.sh
Jenkinsfile.split
tests/common/src/main/java/com/gentics/mesh/test/docker/AWSContainer.java
tests/common/src/main/java/com/gentics/mesh/test/docker/ElasticsearchContainer.java
tests/common/src/main/java/com/gentics/mesh/test/docker/KeycloakContainer.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

This enables test runs to pull the container images not directly from
dockerhub to avoid running into pull rate limits

Add system property to specify test container image prefix.

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/WebrootPathCacheImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webroot/WebRootEndpointPathPrefixTest.java
tests/tests-core/src/main/java/com/gentics/mesh/linkrenderer/BranchLinkRendererTest.java
tests/tests-core/src/main/resources/graphql/branch-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/BranchTypeProvider.java

Port of SUP-13744

---

core/src/main/java/com/gentics/mesh/core/endpoint/admin/debuginfo/providers/MigrationStatusProvider.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/AbstractListFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/html/HtmlFieldListEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/string/StringFieldListEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeImageResizeEndpointETagTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/MicroschemaChangesEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webroot/WebRootEndpointETagTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webrootfield/WebRootFieldEndpointETagTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractNodeSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/ElasticSearchProviderTimeoutTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeSearchEndpointBTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeSearchEndpointCTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeSearchEndpointDTest.java

Mdm fix test timeouts

---

tests/tests-core/src/main/java/com/gentics/mesh/core/field/html/HtmlFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/string/StringFieldEndpointTest.java

No telling apart for empty String and nulls - tests part

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/plugin/manager/MeshPluginManagerImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshRestClientConfig.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestOkHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/monitoring/impl/MonitoringOkHttpClientImpl.java

1. Make sure failed plugin starts are recognized by the liveness check.
2. Add automatic retry configuration for the Mesh REST client.

Hotfix 1.6.x SUP-13786

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/plugin/manager/MeshPluginManagerImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshRestClientConfig.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestOkHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/monitoring/impl/MonitoringOkHttpClientImpl.java

Port of SUP-13786

---

api/README.md
changelog-system/README.md
common-api/README.md
common/README.md
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
databases/README.md
databases/orientdb/README.md
demo/common/README.md
demo/default/README.md
distributed-coordinator/README.md
distributed/README.md
doc/README.md
doc/src/main/docs/administration-guide.asciidoc
doc/src/main/docs/clustering.asciidoc
doc/src/main/docs/logging.asciidoc
doc/src/main/docs/security.asciidoc
elasticsearch/README.md
ferma/README.md
madl/README.md
madl/api/README.md
madl/core/README.md
madl/madl-ferma/README.md
madl/orientdb/README.md
mdm/api/src/main/java/com/gentics/mesh/core/db/TxAction.java
mdm/api/src/main/java/com/gentics/mesh/core/db/TxAction0.java
mdm/api/src/main/java/com/gentics/mesh/core/db/TxAction1.java
mdm/api/src/main/java/com/gentics/mesh/core/db/TxAction2.java
verticles/admin-gui/README.md
verticles/graphql/README.md

Documentation changes for MDM

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/service/AbstractWebRootService.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLWebrootTest.java

Hotfix 1.8.x sup 11419 missing permission for root node in branch

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/UserDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLPublishedMatchingDraftNodePermissionTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLWebrootTest.java
tests/tests-core/src/main/resources/graphql/node-perm-children-query.draft
tests/tests-core/src/main/resources/graphql/node/permissions/rootNode
tests/tests-core/src/main/resources/graphql/node/publishedmatchingdraft/nodePerPath
tests/tests-core/src/main/resources/graphql/node/publishedmatchingdraft/nodePerUuid
tests/tests-core/src/main/resources/graphql/node/publishedmatchingdraft/rootNode
verticles/graphql/src/main/java/com/gentics/mesh/graphql/context/GraphQLContext.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/context/impl/GraphQLContextImpl.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/model/NodeReferenceIn.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/TagTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Port of #1430 for version 1.8.

Hotfix 1.8.x sup 13991 check rootnode permission

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/rest/MeshLocalRequestImpl.java
doc/src/main/docs/java-rest-client.asciidoc
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshBinaryResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshWebrootFieldResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshWebrootResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpWebrootFieldResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpWebrootResponse.java
tests/common/src/main/java/com/gentics/mesh/test/ConnectionVerifier.java
tests/tests-core/src/main/java/com/gentics/mesh/rest/ConnectionLeakTest.java

Port of Fix for SUP-12629

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/MeshVertex.java
common/src/main/java/com/gentics/mesh/error/MissingPermissionException.java
core/src/main/java/com/gentics/mesh/context/impl/NodeMigrationActionContextImpl.java
core/src/main/java/com/gentics/mesh/core/data/generic/MeshVertexImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/GroupImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/ProjectImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/TagFamilyImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/AbstractRootVertex.java
core/src/main/java/com/gentics/mesh/core/data/root/impl/NodeRootImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/role/RoleCrudHandler.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLSearchPermissionTest.java
core/src/test/java/com/gentics/mesh/core/node/NodeTest.java
core/src/test/java/com/gentics/mesh/core/role/RoleEndpointPermissionsTest.java
core/src/test/java/com/gentics/mesh/search/permission/NodePermissionSearchTest.java

Hotfix 1.6.x sup 14243

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/distributed/DistributionUtils.java
tests/tests-distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/RequestDelegatorRegexTest.java

Hotfix 1.8.x sup 12967

---

services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java

Fix OAuth2 access token handling after Vert.x 4 update.

Fix access token handling for new Vert.x 4 User implementation

---

LTS-CHANGELOG.adoc
demo/Dockerfile
server/Dockerfile

The base image for server and demo images has been updated to the latest version.

Update base image

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandlerImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/search/LanguageOverrideSearchTest.java
tests/tests-core/src/main/resources/schemas/languageOverride/pageWithMicronode.json

Hotfix 1.8.x sup 14400

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/NodeGraphFieldContainer.java
core/src/test/java/com/gentics/mesh/core/node/NodeEndpointTest.java
core/src/test/java/com/gentics/mesh/core/node/NodePublishEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
core/src/test/java/com/gentics/mesh/core/tag/TagEndpointTest.java
core/src/test/java/com/gentics/mesh/core/tagfamily/TagFamilyEndpointTest.java
core/src/test/java/com/gentics/mesh/search/LanguageOverrideSearchTest.java
core/src/test/java/com/gentics/mesh/search/NodeBinaryDisabledSearchTest.java
core/src/test/java/com/gentics/mesh/search/NodeBinaryDocumentSearchTest.java
core/src/test/java/com/gentics/mesh/search/NodeBinarySearchTest.java
demo/src/test/java/com/gentics/mesh/demo/DemoDumpGeneratorTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/entity/MeshEntities.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/PermissionChangedEventHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/project/ProjectUpdateEventHandler.java
test-common/src/main/java/com/gentics/mesh/assertj/impl/DummySearchProviderAssert.java

Fix language specific (re-)indexing after moving or tagging a node

---

LTS-CHANGELOG.adoc
demo/common/src/test/java/com/gentics/mesh/demo/AbstractDemoDumperTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandlerImpl.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/entity/MeshEntities.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/PermissionChangedEventHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/project/ProjectUpdateEventHandler.java
mdm/api/src/main/java/com/gentics/mesh/core/data/HibNodeFieldContainer.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
tests/common/src/main/java/com/gentics/mesh/assertj/impl/DummySearchProviderAssert.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodePublishEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/tag/TagEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/tagfamily/TagFamilyEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/LanguageOverrideSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeBinaryDisabledSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeBinaryDocumentSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeBinarySearchTest.java

This is the port of the fix for SUP-14446 to hotfix-1.8.x

Port fix for SUP-14446 to 1.8.x

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/ContentConfig.java
common/src/main/java/com/gentics/mesh/core/data/schema/SchemaContainerVersion.java
core/src/main/java/com/gentics/mesh/core/data/schema/impl/SchemaContainerVersionImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/migration/node/NodeMigrationHandler.java
core/src/test/java/com/gentics/mesh/search/NodeBinaryDocumentMigrationTest.java
core/src/test/java/com/gentics/mesh/search/migration/BatchedNodeMigrationSearchTest.java
core/src/test/java/com/gentics/mesh/test/context/MeshOptionChanger.java
core/src/test/java/com/gentics/mesh/test/context/MeshTestContext.java
core/src/test/java/com/gentics/mesh/test/context/helper/EventHelper.java

Chunked node migrations

---

LTS-CHANGELOG.adoc
server/Dockerfile

Add extra cmd tools to Docker image.

Add extra tools to Docker image

---

Jenkinsfile.split

Test System Changes

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java

Force the uniqueness of Mesh usernames.

Force the uniqueness of Mesh usernames.

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacerImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/NodeDao.java
mdm/api/src/main/java/com/gentics/mesh/core/link/ContentSegment.java
mdm/api/src/main/java/com/gentics/mesh/core/link/LinkContentSegment.java
mdm/api/src/main/java/com/gentics/mesh/core/link/StringContentSegment.java
mdm/api/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacer.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/NodeDaoWrapperImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
tests/tests-core/src/main/resources/graphql/node/link/webroot
tests/tests-core/src/main/resources/graphql/node/link/webroot-medium
tests/tests-core/src/main/resources/graphql/node/link/webroot-medium.v1
tests/tests-core/src/main/resources/graphql/node/link/webroot-short
tests/tests-core/src/main/resources/graphql/node/link/webroot-short.v1
tests/tests-core/src/main/resources/graphql/node/link/webroot.v1
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

and getting referenced nodes from node fields via graphql by using DataLoaders.

Improve performance of link resolving in string/html fields

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacerImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacer.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Fix possible duplicate key error

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingContentDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/ContentDaoWrapperImpl.java
tests/common/src/main/java/com/gentics/mesh/assertj/impl/JsonObjectAssert.java
tests/tests-core/src/main/resources/graphql/node-tag-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Add API for preloading list field values
Omit checking for conflicting url field values, if the values do not change.
Fix graphql test for unordered items (like tags) to not rely on the order.

Add API for preloading list field values

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/cache/impl/EventAwareCacheImpl.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java

Cache breaks on nulls

---

LTS-CHANGELOG.adoc
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/MasterElector.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ClusterConfigEndpointNoClusterTest.java

Fix NPEs when accessing cluster config for non-clustered instances

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacerImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/link/ContentSegment.java
mdm/api/src/main/java/com/gentics/mesh/core/link/LinkContentSegment.java
mdm/api/src/main/java/com/gentics/mesh/core/link/StringContentSegment.java
tests/tests-core/src/main/java/com/gentics/mesh/linkrenderer/LinkReplacerVariationTest.java

mesh links.
Replacing links with replaceMany() did not consider the language tags from the mesh.links.

Fix link replacing with replaceMany to consider language tags from the

---

changelog/src/changelog/entries/2023/08/7541.SUP-15689.bugfix
rest-client/src/main/java/com/gentics/mesh/parameter/client/SortingParametersImpl.java
rest-model/src/main/java/com/gentics/mesh/parameter/SortingParameters.java
tests/tests-core/src/main/java/com/gentics/mesh/core/branch/BranchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/group/GroupEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/role/RoleEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/SchemaEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/tag/TagEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/tagfamily/TagFamilyEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/definition/CrudEndpointTestCases.java

Add tests for sorting entity lists

Fix incorrect implementation of SortingParameters

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/NodeDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/NodeDaoWrapperImpl.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/dataloader/NodeContentWithOptionalRuntimeException.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/dataloader/NodeDataLoader.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java

Speed up the parent GraphQL loading by making a batch call.

SUP-15409: Speed up parent loading the right way

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/ScrollingIterator.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/entry/AbstractIndexHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandlerImpl.java
server/src/main/java/com/gentics/mesh/server/DevRunner.java

The System.out input heavily pollutes the log.

Remove annoying shard output

---

changelog/src/changelog/entries/2023/10/7595.SUP-15895.bugfix
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLMultithreadingTest.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/BinaryFieldFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/EntityReferenceFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/S3BinaryFieldFilter.java

Maps need to be synchronized if modified in concurrent threads.

More synchronization of static maps

---

elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeSearchHandler.java

Fix handling of results in different languages

---

LTS-CHANGELOG.adoc
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/Tag.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/TagFamily.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/TagFamilyImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/TagImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/root/impl/TagFamilyRootImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/NamedEntityDuplicationTest.java
tests/tests-core/src/main/java/com/gentics/mesh/util/CoreTestUtils.java

A set of uniqueness checks against selected named entities has been introduced.

SUP-16041: Name uniqueness tests

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/dataloader/NodeDataLoader.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/model/NodeReferenceIn.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java

Speed up the node reference fields by batching the load.

SUP-16040: Batch load the referencedBy nodes

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/list/HibBooleanFieldList.java
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/list/HibDateFieldList.java
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/list/HibHtmlFieldList.java
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/list/HibNumberFieldList.java
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/list/HibStringFieldList.java
mdm/common/src/main/java/com/gentics/mesh/core/data/node/field/RestUpdaters.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/AbstractFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/FieldTestcases.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/bool/BooleanListFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/date/DateListFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/html/HtmlListFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/number/NumberListFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/string/StringListFieldTest.java

Each list item insertion make a separate query + flush, which is expensive. We avoid this.

SUP-16040: Batch load referencing nodes+edges.

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingGroupDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingLanguageDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingMicroschemaDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingProjectDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRoleDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRootDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingSchemaDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingTagDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingTagFamilyDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
mdm/common/src/main/java/com/gentics/mesh/core/db/TxEntityPersistenceManager.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/db/AbstractTx.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/AbstractCoreDaoWrapper.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/AbstractRootDaoWrapper.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/BranchDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/NodeDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/TagFamilyDaoWrapperImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/node/NodeListFieldTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/job/JobTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/SchemaChangeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/change/AbstractChangeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/change/UpdateMicroschemaChangeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/field/AbstractFieldMigrationTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/WrapperHelper.java

At 1.10.20 the regression appeared, introducing the problems at creating a new named entity. Th e fix comes here.

SUP-16120: Fix the instances initialization

---

changelog/src/changelog/entries/2023/12/7645.SUP-16169.bugfix
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/nativefilter/NativeGraphQLEndpointTest.java
tests/tests-core/src/main/resources/graphql/filtering/children-sorted-by-schema
tests/tests-core/src/main/resources/graphql/filtering/children-sorted-by-schema.v1
tests/tests-core/src/main/resources/graphql/filtering/nodes-sorted-by-schema
tests/tests-core/src/main/resources/graphql/filtering/nodes-sorted-by-schema.v1

Add more test cases for sorting

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/parameter/impl/GenericParametersImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingLanguageDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/language/LanguageTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractMeshTest.java

Small fixes in `fields` REST parameter.

Hotfix 1.10.x sup 15643

---

services/local-storage/src/main/java/com/gentics/mesh/storage/LocalBinaryStorageImpl.java
tests/context-api/src/main/java/com/gentics/mesh/test/MeshTestSetting.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/ssl/SSLTestClient.java
tests/tests-core/src/main/java/com/gentics/mesh/core/ssl/SSLUserCertRequireServerTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/index/BasicIndexSyncTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/migration/BatchedNodeMigrationSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/migration/NodeMigrationSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/EventHelper.java

Various test fixes

---

verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/NodeFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/SchemaFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/MicronodeFieldTypeProvider.java

Since we are more careful with creating (micro)node types with no (micro)schemas, the references to these types should also be taken over.

GraphQL Regression fixes

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/DaoTransformable.java
mdm/common/src/main/java/com/gentics/mesh/core/data/page/PageTransformer.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/ContentDaoWrapperImpl.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Fetching of micronode fields will now use a DataLoader, which allows batch loading.

Implement DataLoader for micronode fields

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/PermissionCacheImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/perm/PermissionCacheTest.java

Fix returning cached permissions as copies

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/context/impl/LocalActionContextImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/AbstractMeshRestHttpClient.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshRestClientConfig.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
tests/context-api/src/main/java/com/gentics/mesh/test/MeshTestSetting.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-rest-client/src/main/java/com/gentics/mesh/rest/RestClientTest.java

Add option to not reset database between test cases

---

Jenkinsfile.split
api/src/main/resources/mesh.build.properties
pom.xml

F gpu 1198

---

bom/pom.xml
doc/src/main/docs/features.asciidoc
doc/src/main/docs/java-rest-client.asciidoc
doc/src/main/docs/plugin-system.asciidoc
rest-client/src/main/java/com/gentics/mesh/rest/client/AbstractMeshRestHttpClient.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestOkHttpClientImpl.java

Reimplement file upload to properly send the Content-Length header

Update Version of OkHttp Client

---

pom.xml
report-assembly.xml
server/pom.xml
server/src/static_dependencies.json

Implement generation of dependency report artifacts

---

changelog/src/changelog/entries/2023/11/7605.GPU-1088.enhancement
common/src/main/java/com/gentics/mesh/auth/provider/MeshJWTAuthProvider.java
core/src/main/java/com/gentics/mesh/core/endpoint/auth/AuthenticationRestHandler.java
rest-client/src/main/java/com/gentics/mesh/rest/JWTAuthentication.java
rest-model/src/main/java/com/gentics/mesh/core/rest/auth/LoginRequest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/AuthenticationEndpointTest.java

GPU-1088: Get session token from API token

---

Jenkinsfile
js/.gitignore
js/.npmrc
js/nx.json
js/package-lock.json
js/package.json
js/packages/mesh-models/package.json
js/packages/mesh-models/project.json
js/packages/mesh-rest-client-angular/package.json
js/packages/mesh-rest-client-angular/project.json
js/packages/mesh-rest-client-angular/tsconfig.json
js/packages/mesh-rest-client/package.json
js/packages/mesh-rest-client/project.json
js/tsconfig.json

Hotfix 2.1.x gpu 1410

---

core/src/main/java/com/gentics/mesh/demo/UserInfo.java
mdm/common/src/main/java/com/gentics/mesh/core/db/TxEntityPersistenceManager.java
tests/tests-core/src/main/java/com/gentics/mesh/cache/ActionContextBranchCacheTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/nativefilter/NativeGraphQLEndpointFilterTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/role/RoleRolePermissionsEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/TestDataProvider.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractRolePermissionEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/TestHelper.java

Fix some test suite parts, that have no respect over cached entities and respectful transaction.

GPU-1578: Test suite refactoring

---

.jenkins/Dockerfile.nexus
.jenkins/build-deploy-test-env.sh
.jenkins/build-env-nexus.sh
.jenkins/files/settings.xml
.jenkins/run-splits.sh
Jenkinsfile
Jenkinsfile.split
doc/src/main/docs/commercial/long-term-support.asciidoc
pom.xml
tests/common/src/main/java/com/gentics/mesh/test/docker/ElasticsearchContainer.java
tests/tests-core/src/main/resources/testcontainers.properties

Hotfix 1.10.x nexus

---

.jenkins/Dockerfile.nexus
.jenkins/build-deploy-test-env.sh
.jenkins/build-env-nexus.sh
.jenkins/run-splits.sh
Jenkinsfile
Jenkinsfile.split
build/settings.xml
doc/src/main/docs/commercial/long-term-support.asciidoc
js/.npmrc
pom.xml
tests/common/src/main/java/com/gentics/mesh/test/docker/ElasticsearchContainer.java
tests/tests-core/src/main/resources/testcontainers.properties

Hotfix 2.1.x nexus

---

bom/pom.xml
changelog/src/changelog/entries/2024/10/7988.SUP-17458.bugfix
pom.xml
tests/tests-core/src/main/resources/graphql/filtering/nodes-boolean-field-native
tests/tests-core/src/main/resources/graphql/filtering/nodes-date-field-native
tests/tests-core/src/main/resources/graphql/filtering/nodes-number-field-native
tests/tests-core/src/main/resources/graphql/filtering/nodes-string-field-native
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/ImageDataFieldFilter.java

Update Version of graphql filter library

---

bom/pom.xml

Hotfix 2.1.x update graphql filter

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
core/src/main/java/com/gentics/mesh/dagger/module/JobProcessingModule.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/JobDao.java
mdm/common/src/main/java/com/gentics/mesh/core/image/ImageManipulator.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/ImageCacheMigrationProcessor.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/job/JobRoot.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/JobDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/DatabaseHelper.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/job/impl/ImageCacheMigrationJobImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/job/impl/JobRootImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/job/JobType.java
services/image-imgscalr/src/main/java/com/gentics/mesh/image/ImgscalrImageManipulator.java
services/local-storage/src/main/java/com/gentics/mesh/storage/LocalBinaryStorageImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeImageResizeEndpointTest.java

Make image cache depth depend on a parameter.

Image cache refactored

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/search/ProjectSearchEndpointImpl.java
core/src/main/java/com/gentics/mesh/search/SearchEndpointImpl.java

SUP-17222: Search query param docu

---

.jenkins/Dockerfile.nexus
Jenkinsfile.split

Added automatic JS building and deployment to CI builds

---

bom/pom.xml
changelog/src/changelog/entries/2024/8054.SUP-17710.bugfix
verticles/graphql/src/main/java/com/gentics/mesh/graphql/dataloader/NodeDataLoader.java

Speed up the graphql queries by correctly merging the contexts.

Hotfix 2.1.x sup 17710

---

changelog/src/changelog/entries/2024/11/8054.SUP-17710.bugfix
changelog/src/changelog/entries/2024/12/8074.SUP-17869.bugfix
changelog/src/changelog/entries/2024/8054.SUP-17710.bugfix
core/src/main/java/com/gentics/mesh/core/data/impl/MeshAuthUserImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/AuthenticationEndpointTest.java

SUP-17869: Fix accessing principal's referenced node

---

doc/src/main/hugo/content/docs/administration-guide.asciidoc

Update the docu with the info on prebuilt Mesh Connector images.

SUP-18056: Update the docu with the actual info on pre-built Mesh images

---

changelog/src/changelog/entries/2025/02/8146.SUP-14730.bugfix
common/src/main/java/com/gentics/mesh/auth/handler/MeshJWTAuthHandler.java
common/src/main/java/com/gentics/mesh/auth/provider/MeshJWTAuthProvider.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/AuthenticationEndpointTest.java

Make JWT Cookie http only

---

bom/pom.xml
changelog/src/changelog/entries/2025/03/8196.SUP-18220.bugfix

Update dependency to nashorn-core

---

changelog/src/changelog/entries/2025/03/8206.SUP-18278.bugfix
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryTransformHandler.java
services/image-imgscalr/src/main/java/com/gentics/mesh/image/ImgscalrImageManipulator.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

The problem arises when a test is started in the scope of an other database context.

SUP-18278: S3BinaryFieldEndpointTest#testTransformS3BinarySuccessful

---

core/src/main/java/com/gentics/mesh/cli/CoreVerticleLoader.java
core/src/main/java/com/gentics/mesh/event/EventBusLivenessManagerImpl.java
mdm/common/src/main/java/com/gentics/mesh/monitor/liveness/EventBusLivenessManager.java
tests/common/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractMeshTest.java

Hotfix 3.0.x gpu 1967

---

core/src/main/java/com/gentics/mesh/cli/CoreVerticleLoader.java
core/src/main/java/com/gentics/mesh/event/EventBusLivenessManagerImpl.java
mdm/common/src/main/java/com/gentics/mesh/monitor/liveness/EventBusLivenessManager.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractMeshTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Improve test stability

---

changelog/src/changelog/entries/2025/03/8211.SUP-18279.bugfix
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/node/NodeContentEventHandler.java

Fix the quickly incoming event trigger request, when deletions and updates are mixed. `BasicIndexSyncTest`.

Hotfix 2.1.x sup 18279

---

changelog/src/changelog/entries/2025/03/8208.SUP-18281.bugfix
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/util/KeycloakUtils.java
tests/common/src/main/resources/keycloak/realm.json
tests/tests-core/src/main/java/com/gentics/mesh/auth/OAuth2KeycloakPluginTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Reload the set of groups/users, changed during the OAuth session.

Hotfix 2.1.x sup 18281

---

tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

Improve test

---

.jenkins/run-splits.sh
LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
demo/common/src/main/java/com/gentics/mesh/demo/AbstractMeshOptionsDemoContext.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Fix creation of files in the binary image cache

---

bom/pom.xml
changelog/src/changelog/entries/2025/04/8229.SUP-18396.bugfix
connectors/api/pom.xml
mdm/hibernate-api/pom.xml
mdm/hibernate-core/pom.xml
server/pom.xml

Fix dependencies and dependency report

---

common-api/src/main/java/com/gentics/mesh/util/MavenVersionNumber.java

Fix the CI runs on custom versions

CI run fix

---

changelog/src/changelog/entries/2025/04/8232.SUP-18387.bugfix
common/src/main/java/com/gentics/mesh/core/s3binary/S3BinaryDataProcessorContext.java
core/src/main/java/com/gentics/mesh/core/endpoint/node/S3BinaryMetadataExtractionHandlerImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/node/S3BinaryUploadHandlerImpl.java
core/src/main/java/com/gentics/mesh/core/s3binary/impl/S3BasicImageDataProcessor.java
core/src/main/java/com/gentics/mesh/core/s3binary/impl/TikaS3BinaryProcessor.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/storage/S3BinaryStorage.java
rest-client/src/main/java/com/gentics/mesh/rest/client/AbstractMeshRestHttpClient.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/NodeBinaryFieldClientMethods.java
services/aws-s3-storage/src/main/java/com/gentics/mesh/core/data/storage/s3/S3BinaryStorageImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/s3binary/S3BinaryFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webroot/WebRootEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webrootfield/WebRootFieldTypeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/linkrenderer/LinkRendererTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/TestHelper.java

Fix the language dependent S3 binaries

Hotfix 2.1.x sup 18387

---

Jenkinsfile.split

Removed dry-deploy for JS packages

---

changelog/src/changelog/entries/2025/07/8322.bugfix
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
tests/context-api/src/main/java/com/gentics/mesh/test/MeshTestSetting.java
tests/context-api/src/main/java/com/gentics/mesh/test/ResetTestDb.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/javafilter/JavaGraphQLEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/nativefilter/NativeGraphQLEndpointFilterTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/nativefilter/NativeGraphQLEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/TestHelper.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/EventHelper.java

Hotfix 2.1.x testfixes

---

changelog/src/changelog/entries/2025/08/8379.SUP-18896.bugfix
core/src/main/java/com/gentics/mesh/dagger/module/PluginModule.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshRestClientConfig.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpClientUtil.java

SUP-18896: Use plugin timeout in the plugin's HTTP client

---

doc/src/main/hugo/content/docs/graphql.asciidoc

Fix incorrect value in navive filtering GraphQL docu

---

changelog/src/changelog/entries/2025/09/8423.SUP-18931.bugfix
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/NodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/root/impl/TagRootImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/NodeChildrenInfo.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeReadPermissionTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/helper/ClientHelper.java

Fix getting children info

---

changelog/src/changelog/entries/2025/09/8423.SUP-18931.bugfix
changelog/src/changelog/entries/2025/09/8424.SUP-18931.bugfix
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/NodeDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
mdm/hibernate-core/src/main/java/com/gentics/mesh/hibernate/data/dao/NodeDaoImpl.java
mdm/hibernate-core/src/main/java/com/gentics/mesh/hibernate/data/domain/HibNodeImpl.java
mdm/hibernate-core/src/main/java/com/gentics/mesh/hibernate/data/loader/DataLoaders.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/NodeChildrenInfo.java
tests/common/src/main/java/com/gentics/mesh/test/context/helper/ClientHelper.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeReadPermissionTest.java

Hotfix 3.0.x sup 18931

---

changelog/src/changelog/entries/2025/09/8446.bugfix
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeIndexHandlerImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NoIndexTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/AbstractMeshTest.java

Hotfix 2.1.x timeout fix

---

changelog/src/changelog/entries/2025/10/8489.SUP-19076.bugfix
elasticsearch/src/main/java/com/gentics/mesh/search/index/entry/AbstractIndexHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/eventhandler/SyncEventHandler.java
tests/tests-core/src/main/java/com/gentics/mesh/search/ElasticSearchProviderTimeoutTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/index/IndexSyncCleanupTest.java

Properly close scroll contexts
