core/pom.xml
pom.xml

Move "mesh.build.timestamp" maven property to root pom to fix build timestamp not displayed on startup.

Fix build timestamp not displayed on startup

---

CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/AuthenticationOptions.java
core/src/main/java/com/gentics/mesh/cli/MeshImpl.java

NPE on startup when keystore path contains no directory eg: keystorePath: "keystore.jceks"

NPE when keystore path contains no directory

---

doc/src/main/docs/building-blocks.asciidoc

Fixed a typo in the ` Building Blocks` page.
Unfortunately, I could not sign the CLA, URL mentioned in CONTRIBUTING.md returns a 404 error page. (https://www.clahub.com/agreements/gentics/mesh)

Doc: fix typo (integeration -> integration)

---

core/pom.xml

(workaround for classpath issues in plugin management, which does not
allow the formplugin to use its own version of commons-csv)

Add dependency on commons-csv

---

databases/orientdb/pom.xml

add hazelcast kubernetes autodiscovery plugin:
modify your hazelcast.xml this way:
```
<network>
<port auto-increment="true">5701</port>
<join>
<multicast enabled="false"/>
<tcp-ip enabled="false" />
<discovery-strategies>
<discovery-strategy enabled="true"
class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
<properties>
<property name="service-dns">defined by env variable (hazelcast.kubernetes.service-dns)</property>
<property name="service-dns-timeout">500</property>
</properties>
</discovery-strategy>
</discovery-strategies>
</join>
</network>
```

feat: add hazelcast kubernetes discovery plugin

---

CHANGELOG.adoc
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/TopologyEventBridge.java

Adding the mesh version to the node name causes orientdb to add bogus entries to its distributed-config.json file which lists all known nodes.

Remove mesh version from node name

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacer.java
core/src/test/java/com/gentics/mesh/linkrenderer/LinkRendererEndpointTest.java

Happened if the branch parameter is passed.

Fix ignored language parameter in link rendering

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/generic/PermissionProperties.java
core/src/test/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelper.java

This NPE was thrown if a project was attempted to be created after any role with permissions to create projects was deleted:
```
16:37:02.181 [] ERROR [vert.x-eventloop-thread-9] [c.g.m.r.r.FailureHandler] - Error for request in path: /api/v1/projects
16:37:02.181 [] ERROR [vert.x-eventloop-thread-9] [c.g.m.r.r.FailureHandler] - Error:
java.lang.NullPointerException: null
at com.gentics.mesh.core.data.impl.UserImpl.addPermissionsOnRole(UserImpl.java:504)
at com.gentics.mesh.core.data.impl.UserImpl.addCRUDPermissionOnRole(UserImpl.java:496)
at com.gentics.mesh.core.data.root.impl.ProjectRootImpl.create(ProjectRootImpl.java:210)
at com.gentics.mesh.core.data.root.impl.ProjectRootImpl.create(ProjectRootImpl.java:44)
at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$null$4(Hand …
```

Fix internal server error when creating project after certain conditions

---

CHANGELOG.adoc
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java

GraphQL errors have not been handled, causing `io.reactivex.exceptions.OnErrorNotImplementedException`.

Send GraphQL errors to client

---

CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/util/VersionNumber.java
common/src/main/java/com/gentics/mesh/context/impl/DummyEventQueueBatch.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/HighLevelChangesList.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java
core/src/main/java/com/gentics/mesh/core/data/container/impl/MicroschemaContainerVersionImpl.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLEndpointBranchTest.java
core/src/test/java/com/gentics/mesh/core/schema/MicroschemaMigrationTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelper.java
core/src/test/java/com/gentics/mesh/test/context/helper/ClientHelper.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/FieldMap.java

Fixes microschema migration by fixing the MicroschemaContainerVersionImpl#getDraftFieldContainers method.
Fixes #979 Fixes #1014 Fixes #1025

Microschema migration fix

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/parameter/impl/ImageManipulationParametersImpl.java
common/src/test/java/com/gentics/mesh/query/impl/ImageManipulationParametersTest.java
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryFieldResponseHandler.java
core/src/test/java/com/gentics/mesh/core/node/NodeImageResizeEndpointTest.java
doc/src/main/docs/image-manipulation.asciidoc
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/BinaryFieldTransformRequest.java
rest-model/src/main/java/com/gentics/mesh/parameter/ImageManipulationParameters.java
services/image-imgscalr/src/main/java/com/gentics/mesh/image/ImgscalrImageManipulator.java

Mesh supports now the auto value in height or width. The changes are done in the Image Manipulation and in BinaryFieldResponse. The height and width are now strings.

Auto feature image manipulation hotfix 1.4.x

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/schema/GraphFieldSchemaContainerVersion.java
core/src/main/java/com/gentics/mesh/core/endpoint/branch/BranchCrudHandler.java

When migrating, currently only schemas that are active to the branch are considered for migration. Under certain circumstances, other older nodes can exist. This fix ensures that these older Nodes are migrated as well.

Include all previous schema versions when migrating remaining nodes 

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/context/AbstractInternalActionContext.java
common/src/main/java/com/gentics/mesh/context/InternalActionContext.java
common/src/main/java/com/gentics/mesh/router/route/AbstractInternalEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminHandler.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/RestInfoEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/debuginfo/providers/StatusProvider.java
core/src/main/java/com/gentics/mesh/core/endpoint/handler/AbstractHandler.java
core/src/test/java/com/gentics/mesh/core/RestInfoEndpointTest.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLMeshTypeTest.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/MeshTypeProvider.java

Add perm checks for server tokens to always allow admin users to see the tokens.

Add perm checks for server tokens

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/admin/plugin/PluginHandler.java

Removes the write lock from plugin deploy and undeploy methods. The lock inside there could conflict with the lock that is potentially needed during plugin initialization.

Fix deadlock situation when handling plugins

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/admin/consistency/check/BinaryCheck.java
core/src/test/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

Uploading a binary with size 0 should not cause an inconsistency in the `/admin/consistency/check` endpoint.

Allow empty binaries without inconsistency

---

CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacer.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/test/java/com/gentics/mesh/linkrenderer/BranchLinkRendererTest.java
core/src/test/java/com/gentics/mesh/linkrenderer/ResolveLinksEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/TestHelper.java
doc/src/main/docs/features.asciidoc
rest-model/src/main/java/com/gentics/mesh/core/rest/branch/BranchResponse.java

Resolving mesh links to nodes in the same project and branch should return a relative URL as already documented here: https://getmesh.io/docs/features/#crossdomainlinks

Resolve to relative URLs when referencing a node in the same branch

---

CHANGELOG.adoc
core/src/test/java/com/gentics/mesh/search/NodeSearchEndpointATest.java
core/src/test/java/com/gentics/mesh/search/raw/NodeRawSearchEndpointTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerMappingProvider.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerTransformer.java

Adds extra field to search index so that the search plugin can better identify branches for search hits.

Add branchUuid to node search index documents

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java
core/src/test/java/com/gentics/mesh/core/monitoring/MonitoringServerEndpointTest.java
core/src/test/java/com/gentics/mesh/plugin/FailingShutdownPlugin.java

Adds plugin status checks to the readiness probe. This way mesh will only indicate that it is ready when all plugins have been registered.

Add check for failed plugin deployments

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/test/java/com/gentics/mesh/core/user/UserEndpointTest.java

Fixes part of #1114 
See `UserEndpointTest#testUpdateNodeReferenceTwice` for the test

Allow user to change its node reference

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java
core/src/test/java/com/gentics/mesh/core/monitoring/MonitoringServerEndpointTest.java

Adds liveness probe checks for failed plugins. This way K8S will restart the pod whenever a plugin deployment fails.

Add liveness probe check for failed plugins

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java

Fixes issues with rolling updates in which the write quorum was not yet full-filled and thus plugins have not been deployment.

Fix deployment issues in cluster setups

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/RestructureWebrootIndex.java
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
core/src/test/java/com/gentics/mesh/linkrenderer/ResolveUrlFieldsTest.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/NodeGraphFieldContainer.java
mdm/orientdb-api/src/main/java/com/gentics/mesh/core/data/dao/ContentDaoWrapper.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/ContentDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/ContentWrapper.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/list/impl/StringFieldListImpl.java

If a link cannot be resolved via segment fields, url fields should be used as a fallback, if they exist.
This happens if a node or one of its ascendents has no segment field set.

Use url fields for link resolving as fallback

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/path/Path.java
core/src/main/java/com/gentics/mesh/cache/WebrootPathCacheImpl.java
core/src/main/java/com/gentics/mesh/dagger/MeshComponent.java
core/src/test/java/com/gentics/mesh/core/webroot/WebRootEndpointTest.java

Improves webroot cache entry error handling by validating graph elements within the cache entries.

Improve webroot cache error handling

---

LTS-CHANGELOG.adoc
changelog-system/src/main/java/com/gentics/mesh/changelog/ChangelogSystem.java
common/src/main/java/com/gentics/mesh/cli/BootstrapInitializer.java
common/src/main/java/com/gentics/mesh/graphdb/cluster/ClusterManager.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/HighLevelChangelogSystem.java
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java

This change prevents nodes from joining a cluster which has an outdated database. The changelog should not be executed by joining members to prevent concurrency issues during the startup process.
This fix addresses the problem of upgrading cluster members without applying the changelog.

Add cluster changelog check

---

LTS-CHANGELOG.adoc
distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/proxy/RequestDelegatorImpl.java

Disable request delegation when clustering is not enabled.

Add check for disabled clustering

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/data/NodeGraphFieldContainer.java
core/src/main/java/com/gentics/mesh/changelog/highlevel/change/RestructureWebrootIndex.java
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/migration/branch/BranchMigrationHandler.java
core/src/test/java/com/gentics/mesh/linkrenderer/ResolveUrlFieldsTest.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/list/impl/StringFieldListImpl.java

Backports https://github.com/gentics/mesh/pull/1129 to hotfix-1.6.x
Java  9 specific API calls had to be changed in order to work with Java 8

Use url fields for link resolving as fallback - Backport of PR 1129

---

LTS-CHANGELOG.adoc
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
core/src/test/resources/graphql/node-breadcrumb-query-with-lang
core/src/test/resources/graphql/node-breadcrumb-query-with-lang.v1
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java

Add the `lang` parameter to `breadcrumb` fields for easier language fallback (e.g. when the loaded node itself is german, but all containing folders are english).
This is a pure GraphQL change.

SUP-10440 GraphQL: Add lang parameter to breadcrumb

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java

Fixes database already opened exception in OrientDB server

Fix orientdb studio usage in non-clustered mode

---

LTS-CHANGELOG.adoc
bom/pom.xml

Update OrientDB version to v3.1.10. https://github.com/gentics/mesh/pull/1173

Bump OrientDB version to v3.1.10

---

LTS-CHANGELOG.adoc
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
common/src/main/resources/i18n/translations_zh.properties
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryUploadHandler.java
core/src/test/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

Currently Mesh API returns HTTP 500 error on an empty file upload attempt. We want to make this error more user friendly.

Correctly message out empty file upload

---

databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java

Trace level of logging is useless for getting the reasons and details of the DB transaction retries.

SUP-11433: Log transaction retries better

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/graphdb/cluster/ClusterManager.java
common/src/main/java/com/gentics/mesh/plugin/manager/MeshPluginManager.java
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java
core/src/main/java/com/gentics/mesh/plugin/manager/MeshPluginManagerImpl.java
core/src/main/java/com/gentics/mesh/plugin/registry/DelegatingPluginRegistryImpl.java
core/src/test/java/com/gentics/mesh/plugin/BackupPlugin.java
core/src/test/java/com/gentics/mesh/plugin/PluginManagerClusterTest.java
core/src/test/java/com/gentics/mesh/plugin/PluginManagerTest.java
core/src/test/java/com/gentics/mesh/test/context/helper/EventHelper.java
core/src/test/java/com/gentics/mesh/test/context/helper/ExpectedEvent.java
core/src/test/plugins/failing-first/pom.xml
core/src/test/plugins/failing-first/src/main/java/com/gentics/mesh/plugin/FailingFirstPlugin.java
core/src/test/plugins/init-mutating/pom.xml
core/src/test/plugins/init-mutating/src/main/java/com/gentics/mesh/plugin/InitMutatingPlugin.java
core/src/test/plugins/pom.xml
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java
distributed/src/test/java/com/gentics/mesh/distributed/AbstractClusterTest.java
distributed/src/test/java/com/gentics/mesh/distributed/ClusterTorturePluginHoldsStartup.java
distributed/src/test/java/com/gentics/mesh/distributed/PluginClusterTest.java
rest-model/src/main/java/com/gentics/mesh/core/rest/plugin/PluginStatus.java

Plugins are automatically initialized when a Mesh instance starts. If the initialization fails, because the cluster topology changes (which will cause DB storages to become unavailable), the plugins will now be marked as FAILED_RETRY (instead of FAILED), and plugin initialization of those plugins will be retried as soon as the DB storages are available again.
Additionally, plugins in state FAILED_RETRY will not cause the health check of the instance to fail.

Implement plugin initialization retry if plugin init fails due to

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/ClusterOptions.java
common/src/main/java/com/gentics/mesh/core/verticle/handler/WriteLockImpl.java
common/src/main/java/com/gentics/mesh/distributed/DistributionUtils.java
common/src/main/java/com/gentics/mesh/distributed/TopologyChangeReadonlyHandler.java
common/src/main/java/com/gentics/mesh/graphdb/cluster/ClusterManager.java
common/src/main/java/com/gentics/mesh/router/APIRouter.java
common/src/main/java/com/gentics/mesh/router/RouterStorage.java
common/src/main/java/com/gentics/mesh/router/route/FailureHandler.java
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
common/src/main/resources/i18n/translations_zh.properties
core/src/main/java/com/gentics/mesh/dagger/module/BindModule.java
core/src/test/java/com/gentics/mesh/distributed/TopologyChangeReadonlyTest.java
core/src/test/java/com/gentics/mesh/etc/RouterStorageTest.java
distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/proxy/RequestDelegatorImpl.java
distributed-coordinator/src/test/java/com/gentics/mesh/distributed/coordinator/RequestDelegatorRegexTest.java
distributed/src/main/java/com/gentics/mesh/distributed/TopologyChangeReadonlyHandlerImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/error/AbstractRestException.java

When using the topology lock, all requests will be blocked (at transaction commit) while e.g. a OrientDB sync is running to synchronize a new joining cluster node.
This leads to unavailability of Mesh during the sync (even for reading requests) and can further lead to OOM errors.
The new setting cluster.topologyChangeReadOnly is an alternative, which will let reading requests pass and will respond to writing requests with a 503 immediately.

Implement topology change readonly behaviour

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/GraphStorageOptions.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java

Timeout for joining the cluster was hardcoded to 500 seconds and can now be configured.

Add configuration option for cluster join timeout

---

verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

This is a bugfix for this bug: Caused by: graphql.AssertException: type S3BinaryField not found in schema
The bug is caused by not handling the field in GraphQL.
https://jira.gentics.com/browse/SUP-11537

SUP-11537/bugfix/fix permission issue in S3

---

core/src/main/java/com/gentics/mesh/core/endpoint/node/S3BinaryUploadHandlerImpl.java

This is a bugfix for this bug: [c.g.m.g.OrientDBDatabase] - com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #319:0: found duplicated key '39a8e51a10e24f36a288301162194040/file' in index 'S3BinaryImpl' previously assigned to the record #318:0
https://jira.gentics.com/browse/SUP-11538#

SUP-11538/fix for the update issue in the S3 field

---

LTS-CHANGELOG.adoc
bom/pom.xml
server/.gitignore

The [update v1.5.6](https://github.com/hazelcast/hazelcast-kubernetes/releases/tag/v1.5.6) of Hazelcast-Kubernetes librtary contains an important fix for newer Hazelcast versions regarding DNS resolving within some cluster nodes.

Hazelcast-Kubernetes -> v1.5.6

---

LTS-CHANGELOG.adoc
bom/pom.xml

The [update v1.5.6](https://github.com/hazelcast/hazelcast-kubernetes/releases/tag/v1.5.6) of Hazelcast-Kubernetes librtary contains an important fix for newer Hazelcast versions regarding DNS resolving within some cluster nodes.

Hazelcast-Kubernetes updated to v1.5.6

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/schema/impl/UpdateFieldChangeImpl.java
core/src/test/java/com/gentics/mesh/core/field/string/StringFieldEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/SchemaChangesEndpointTest.java
core/src/test/java/com/gentics/mesh/core/schema/change/AddFieldChangeTest.java
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/change/impl/SchemaChangeModel.java

A bug has appeared to ignore schema updates where the "allow" field restrictions are set to empty.

The field restrictions cannot be unset

---

LTS-CHANGELOG.adoc
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/TopologyEventBridge.java

Get db status from distributed manager, instead of

---

Jenkinsfile
Jenkinsfile.split
common/src/main/java/com/gentics/mesh/core/link/WebRootLinkReplacerImpl.java
core/pom.xml
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/RootDao.java
tests/common/src/main/java/com/gentics/mesh/test/category/ClusterTests.java
tests/common/src/main/java/com/gentics/mesh/test/category/PluginTests.java
tests/common/src/main/java/com/gentics/mesh/test/docker/MeshContainer.java
tests/tests-core/src/main/java/com/gentics/mesh/core/admin/AdminPluginEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLPluginTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/job/JobTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/plugin/AbstractPluginTest.java
tests/tests-core/src/main/java/com/gentics/mesh/plugin/PluginManagerClusterTest.java
tests/tests-core/src/main/java/com/gentics/mesh/plugin/PluginManagerTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/BasicClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ChaosClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ClusterConcurrencyTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ClusterConfigEndpointTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ClusterCoordinatorPlaneTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ClusterCoordinatorTokenTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/ErrorHandlingClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/MultiNodeClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/NodeRejectionClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/PluginClusterTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/SplitBrainTest.java
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/coordinatortoken/ClusterCoordinatorTokenTest.java

Fixes to improve the unit tests' stability. Consist of
* categorizing the environment-dependent UTs (plugins, cluster)
* disabling test split run by default, because of the instability
* fixing the paths to the test plugins

CL-696: Split the BootstrapInitializer #4: unit tests adapt

---

LTS-CHANGELOG.adoc
bom/pom.xml

Update OrientDB to v3.1.13. No extra data migration requirement is expected.

Update OrientDB to v3.1.13

---

plugin-parent/pom.xml

During building Maven complains that the dependency to `mesh-service-jwt-auth` is declared multiple times. This change removes the superfluous declaration.

Fix plugin parent

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/migration/AbstractMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/endpoint/migration/branch/BranchMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/endpoint/migration/micronode/MicronodeMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/endpoint/migration/node/NodeMigrationHandler.java

by using a Queue instead of a List of objects to be migrated
and removing migrated objects from the Queue.
Migration Jobs used a List of the objects to be migrated. During the migration, the objects were "enriched" with additional data which had all to be kept in memory (because the objects were kept in the List).
This has been changed from a List to a Queue, from which the objects are removed before actually migrated.

Fix memory consumption during migrations

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/event/EventQueueBatch.java
common/src/main/java/com/gentics/mesh/event/impl/EventQueueBatchImpl.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/ElasticsearchProcessVerticle.java

with localConsumer
A bug in vert.x causes the handler for eventbus messages to be called in all Mesh instances, even if the handler was registered with localConsumer(). This has been workarounded by adding a header to the message for identifying the sender and a check in the "local" consumer to ignore messages sent by other Mesh instances.

Implement workaround for vert.x incorrectly handling non-local messages

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/verticle/AbstractJobVerticle.java
core/src/main/java/com/gentics/mesh/cli/CoreVerticleLoader.java

run jobs with executeBlocking (which enables immediate publishing of
events)
When the JobWorkerVerticle was deployed as worker verticle, eventbus messages published during the job execution were not published immediately. This seems to be caused by the fact, that the job execution itself is implemented in an event handler.
The JobWorkerVerticle is now no longer deployed as worker verticle, but job execution is now run as executeBlocking(), eventbus messages are now published immediately as expected.

Change jobverticle to be no worker verticle, but to

---

LTS-CHANGELOG.adoc
changelog-system/src/main/java/com/gentics/mesh/changelog/ChangelogSystem.java

with the "normal" transaction, which fixes a possible
OConcurrentModificationException during a rolling update.
When doing a rolling update with a new db revision, the first updated instance would write the new db revision into the MeshRootImpl. The second updated instance would get the change via a sync, and would also try to update the db revision, which caused a OConcurrentModificationException.
The mechanism writing the db revision has been changed to use the "normal" transaction, which fixes the problem.

Fix changelog system to store database revision and Mesh version

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/DiskQuotaOptions.java
api/src/main/java/com/gentics/mesh/etc/config/GraphStorageOptions.java
common/src/main/java/com/gentics/mesh/graphdb/spi/Database.java
common/src/main/java/com/gentics/mesh/rest/impl/InternalEndpointRouteImpl.java
common/src/main/java/com/gentics/mesh/router/route/AbstractInternalEndpoint.java
common/src/test/java/com/gentics/mesh/OptionsLoaderTest.java
core/src/main/java/com/gentics/mesh/core/endpoint/handler/MonitoringCrudHandler.java
core/src/test/java/com/gentics/mesh/rest/EndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/MeshTestContext.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBDatabase.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/OrientDBStorageMetric.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/check/DiskQuotaChecker.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManager.java
databases/orientdb/src/test/java/com/gentics/mesh/graphdb/orientdb/DiskQuotaCheckerTest.java
doc/src/main/docs/administration-guide.asciidoc
doc/src/main/docs/monitoring.asciidoc
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java
test-common/src/main/java/com/gentics/mesh/mock/MockingLoggerRule.java

When the disk, where the OrientDB database is located becomes full, this may cause a corruption of the database. To avoid this, a periodic check for available disk space has been added, which will log warnings (if less than the "warn" threshold is available) or log errors and set Mesh to be read-only (if less than the "read-only" threshold is available).

Add periodic disk quota check.

---

CHANGELOG.adoc
LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/S3Options.java
services/aws-s3-storage/src/main/java/com/gentics/mesh/storage/s3/S3BinaryStorageImpl.java
tests/common/src/main/java/com/gentics/mesh/test/docker/AWSContainer.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Allow CORS options being configured for AWS S3. This will also fix our unit tests based on MINIO. This fix can also be ported to dev/hotfix.

Configure CORS for S3

---

core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
core/src/main/java/com/gentics/mesh/core/data/impl/GroupImpl.java
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/GroupDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/RoleDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/UserDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/group/HibGroup.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingGroupDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingRoleDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingSchemaDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/GroupDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/RoleDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/UserDaoWrapperImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/index/BasicIndexSyncTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/TestDataProvider.java

Scope of this change is to extract business logic to PersistingDao for the User/Group/Role entities

CL-648 extract common logic to persisting dao: user/role/group

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/search/DevNullSearchProvider.java
common/src/main/java/com/gentics/mesh/search/SearchProvider.java
common/src/main/java/com/gentics/mesh/search/TrackingSearchProvider.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminHandler.java
core/src/test/java/com/gentics/mesh/search/ElasticSearchProviderTest.java
elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/MeshTypeProvider.java

elasticsearch is not available.
Calling /api/v1 will try to fetch the elasticsearch version, which failed if elasticsearch was not available.
This change will still log the error, but will not fail in such cases.

Getting the elasticsearch version will not fail in all cases, when

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/router/ProjectsRouter.java
core/src/test/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
core/src/test/java/com/gentics/mesh/core/project/ProjectInfoEndpointTest.java

routes (like /projects).
When a new project is created, a subrouter for the project specific routes is added to the base router at mount point /[projectname]. This subrouter would then also be used for routes *beginning* with /[projectname], so e.g. if a project with name "project" was created, the subrouter would be mounted at /project and would also handle calls to the static router /projects.
If the project was deleted afterwards, calls to /projects would then fail with 404, because the subrouter would try to find the project named "project".
This has been fixed now by mounting the subrouter at path /[projectname]/ (note the end slash).
Calls to /[projectname] (which would load the project by name) are handled by another router, so will still work.

Fix mounting the subrouters for a project to not interfere with static

---

LTS-CHANGELOG.adoc
demo/Dockerfile
server/Dockerfile

Switch base Image from JRE to JDK to have more JDK analyzing tools (like jmap for heapdumps) available)
Update Docker base Image to JDK 11.0.12 (adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.12_7)

Update Docker base Image to JDK 11.0.12

---

Jenkinsfile.split

Currently it's not possible to deploy a maven artifact without other causing other side effects (additional commits, updated pom versions, etc.). However, in the context of mdm, it's useful to be able to deploy snapshots artifacts

add possibility to deploy maven artifact

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/migration/micronode/MicronodeMigrationHandler.java
core/src/test/java/com/gentics/mesh/core/schema/MicroschemaMigrationTest.java

Micronode migrations of nodes, which have different published and draft versions should migrate the old published into the new published, and the old draft into the new draft version.
Before this fix, the new published version was based on the old draft version instead.

Fix micronode migration of published nodes

---

LTS-CHANGELOG.adoc
bom/pom.xml

Uploading documents could fail with an error, if the document contents was parsed with tika, due to incompatilities between tika and the included commons-codec.

Update commons-codec to fix errors in Tika

---

CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/HttpServerConfig.java
core/src/main/java/com/gentics/mesh/rest/RestAPIVerticle.java

With the update to Vert.x 3.9.12 came a change that sets a size limit on the parts of a multipart requests, which causes trouble for Mesh plugins which accept multipart form requests.

Add max form attribute setting (default: unlimited)

---

CHANGELOG.adoc
plugin-api/src/main/java/com/gentics/mesh/plugin/RestPlugin.java
tests/tests-core/src/main/java/com/gentics/mesh/core/admin/AdminPluginEndpointTest.java

Vert.x's StaticHandler will fail to be created with an absolute path, if root filesystem access is not allowed.
Because the StaticHandler for serving files from the plugin's classpath will use the configured plugin directory as base,
the flag to allow root filesystem access will be set, if the plugin directory is absolute.

Allow root filesystem access for the static handler, if necessary

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java

All write operations executed during startup need to wait for the write quorum (if clustering is enabled).

Fix resetting admin password to wait for write quorum

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/root/impl/UserRootImpl.java
core/src/test/java/com/gentics/mesh/core/user/UserEndpointTest.java
core/src/test/java/com/gentics/mesh/test/context/helper/ClientHelper.java
core/src/test/java/com/gentics/mesh/test/context/helper/EventHelper.java

Creation of a new user should only fail for "non-admin" users, if setting the admin flag to "true", but not when setting it to "false".

Fix permission check for creating user with admin set to false.

---

LTS-CHANGELOG.adoc
common/src/main/resources/i18n/translations_de.properties
common/src/main/resources/i18n/translations_en.properties
core/src/main/java/com/gentics/mesh/cache/ProjectNameCacheImpl.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminHandler.java
core/src/main/java/com/gentics/mesh/rest/MeshLocalClientImpl.java
core/src/test/java/com/gentics/mesh/core/admin/AdminEndpointTest.java
core/src/test/java/com/gentics/mesh/core/project/ProjectEndpointTest.java
distributed/src/main/java/com/gentics/mesh/distributed/DistributedEventManager.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/method/AdminClientMethods.java
rest-model/src/main/java/com/gentics/mesh/core/rest/MeshEvent.java

Add REST Endpoint to clear all internal caches
The internal project name cache needs to be properly invalidated if the project is renamed.

Fix clearing the project name cache when a project is renamed.

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/rest/InternalEndpointRoute.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/auth/AuthenticationEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/branch/BranchEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/group/GroupEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/microschema/MicroschemaEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/navroot/NavRootEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/node/NodeEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/project/ProjectEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/project/ProjectInfoEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/role/RoleEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/schema/ProjectSchemaEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/schema/SchemaEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/tagfamily/TagFamilyEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/user/UserEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/utility/UtilityEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/webroot/WebRootEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/webrootfield/WebRootFieldEndpoint.java
core/src/main/java/com/gentics/mesh/search/SearchEndpointImpl.java

Blocking handlers can be added to vert.x "ordered" (which is the default) and "unordered". If the blocking handlers are added "ordered", they will be queued, if other handlers ("ordered" or "unordered") are currently executed.
Many blocking handlers for read-only request were added by default as "ordered", but this is unnecessary and just gets too many requests being queued.

Fix blocking handlers for reading request to not be executed ordered

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
api/src/main/java/com/gentics/mesh/etc/config/VertxEventBusOptions.java
api/src/main/java/com/gentics/mesh/etc/config/VertxOptions.java
common/src/main/java/com/gentics/mesh/event/EventBusLivenessManagerImpl.java
common/src/main/java/com/gentics/mesh/monitor/liveness/EventBusLivenessManager.java
core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java
core/src/main/java/com/gentics/mesh/dagger/MeshComponent.java
core/src/main/java/com/gentics/mesh/dagger/module/BindModule.java
rest-model/src/main/java/com/gentics/mesh/core/rest/MeshEvent.java

Some errors seen on different installations might be caused by the vert.x eventBus, which seem to stop working (event handlers are not called any more). Therefore, a periodic check has been added, which will log warn or error messages, if regular ping events are not handled within a given threshold time.
If ping events are not handled within the given error threshold time, the mesh instance will be considered unhealthy (liveness check will fail).

Add periodic liveness check for vert.x eventBus.

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/DiskQuotaOptions.java

The default threshold values for the disk quota checker have been made absolute (3G for warn and 1G for read-only).

Change defaults for disk quota checker

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/WebrootPathCacheImpl.java
core/src/main/java/com/gentics/mesh/core/data/node/impl/NodeImpl.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
core/src/test/java/com/gentics/mesh/core/webroot/WebRootEndpointPathPrefixTest.java
core/src/test/java/com/gentics/mesh/linkrenderer/BranchLinkRendererTest.java
core/src/test/resources/graphql/branch-query
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/BranchTypeProvider.java

If a branch has a pathPrefix set, it must be used for all links, regardless of how the link is rendered (using segment fields or a url field).

Fix rendering links from url fields: prepend with branch pathPrefix

---

core/src/main/java/com/gentics/mesh/core/endpoint/project/ProjectCrudHandler.java
tests/api/src/main/java/com/gentics/mesh/test/MeshOptionsProvider.java
tests/api/src/main/java/com/gentics/mesh/test/MeshProviderOrder.java

This adds the possibilities to support multiple implementations of MeshOptionsProvider for tests. The classes can be annotated with MeshProviderOrder (for defining, in which order the provider implementations will be checked) and can have a static method "isEligible", which should return true, if the implementation can be used.

Test improvements

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/context/impl/ContextDataRegistryImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationInBranchTest.java

Always take from the NodeMigrationActionContext, even if a project was
given.

Fix getting current branch if running a migration:

---

core/src/main/java/com/gentics/mesh/core/migration/impl/NodeMigrationImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/field/AbstractFieldMigrationTest.java

Fix migration tests to not use nested transactions

Fix NodeMigration to reload data from context

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
core/src/main/java/com/gentics/mesh/plugin/registry/DelegatingPluginRegistryImpl.java
databases/orientdb/src/main/java/com/gentics/mesh/graphdb/cluster/OrientDBClusterManagerImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/db/cluster/ClusterManager.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/cli/OrientDBBootstrapInitializerImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/plugin/AbstractPluginTest.java
tests/tests-distributed/pom.xml
tests/tests-distributed/src/main/java/com/gentics/mesh/distributed/PluginClusterTest.java

As reaching the write quorum is not enough for the plugins to be initialized, when a DB usage is required, the restriction has been upgraded to wait for the local database node reported online.

Plugin initialization depends on database online status

---

CHANGELOG.adoc
rest-model/src/main/java/com/gentics/mesh/core/rest/schema/FieldSchemaContainer.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeWebRootConflictEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/SchemaModelTest.java

Add a few tests for case sensitivity.
Test one check that the segment field content is unique considering casing.
Test two check that it's possible to create two fields with the same name, but different casing. Interestingly, this is allowed in the rest api, but the mesh ui will complain about that

add tests for case sensitity

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/service/WebRootServiceImpl.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLWebrootTest.java

The webroot service root container resolution was flawed, since it didn't take into account branch and container type. This could cause permission issues in graphql when retrieving the root node in a branch that wasn't the default one

fix permission checks for root node

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java
core/src/test/java/com/gentics/mesh/core/graphql/GraphQLPublishedMatchingDraftNodePermissionTest.java
core/src/test/resources/graphql/node-perm-children-query.draft
core/src/test/resources/graphql/node/publishedmatchingdraft/nodePerPath
core/src/test/resources/graphql/node/publishedmatchingdraft/nodePerUuid
core/src/test/resources/graphql/node/publishedmatchingdraft/rootNode
verticles/graphql/src/main/java/com/gentics/mesh/graphql/context/GraphQLContext.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/context/impl/GraphQLContextImpl.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/model/NodeReferenceIn.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/AbstractTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/ProjectTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/SchemaTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/TagTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/UserTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Rootnode informations was returned in graphql even if user requested a draft version without having draft permissions

Hotfix 1.6.x sup 13991 check rootnode permission

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/node/S3BinaryMetadataExtractionHandlerImpl.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerMappingProviderImpl.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerTransformer.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/s3binary/S3BinaryFieldEndpointTest.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Manipulating S3 fields with an index engine ends up in various errors within Mesh and its callers. This fixes the index engine support.

Implement missing S3 binary support for index engine, causing publish process to fail

---

doc/pom.xml

The documentation for environment variables (https://getmesh.io/docs/administration-guide/#env) is generated from code using reflection. Version 1.8 introduced some changes with the test dependencies that, as a side effect, made available some test environment variables in the classpath, leading to the generation of documentation for these bogus variables.
Removing the test dependency fixes the issue.

Hotfix 1.8.x sup 14120

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/rest/MeshLocalRequestImpl.java
core/src/test/java/com/gentics/mesh/rest/ConnectionLeakTest.java
core/src/test/java/com/gentics/mesh/rest/ResourceLeakTest.java
doc/src/main/docs/java-rest-client.asciidoc
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshBinaryResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshWebrootFieldResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/MeshWebrootResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpWebrootFieldResponse.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpWebrootResponse.java
test-common/src/main/java/com/gentics/mesh/test/ConnectionVerifier.java

Incorrect usage of the Java Mesh Client might lead to connection leaks, which have been addressed in the documentation.
Also the MeshWebrootResponse and MeshWebrootFieldResponse classes now have a close() method which closes the underlying Response.

Fixes, tests and documentation for resource leaks problems

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
api/src/main/java/com/gentics/mesh/etc/config/env/EnvironmentVariable.java
api/src/main/java/com/gentics/mesh/etc/config/env/OptionUtils.java

By default every environment variable value is logged on startup. This merge requests add an option for sensitive variables, which value won't be logged.

Hotfix 1.6.x sup 11468

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/cache/impl/EventAwareCacheFactory.java
common/src/main/java/com/gentics/mesh/cache/impl/EventAwareCacheImpl.java
common/src/main/java/com/gentics/mesh/event/EventBusStore.java
core/src/main/java/com/gentics/mesh/cache/PermissionCacheImpl.java
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/cli/OrientDBBootstrapInitializerImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/cache/EventAwareCacheTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webroot/WebRootClusteredEndpointTest.java

Since 1.8.x, starting a cluster with initCluster flag set to true in clustered mode would initliaze caches too early, and as a result they are not connected to the event bus. This has been fixed by making sure the caches subscribe to the latest available event bus. As a consequence of the refactoring, we don't need to initialize vert.x twice anymore

Hotfix 1.8.x sup 14224

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/MeshUploadOptions.java
common/src/main/java/com/gentics/mesh/router/route/FailureHandler.java

For requests which result in a 4xx HTTP status code, additional error messages are logged, which do not add information to the warnings logged by the logger handler. These messages are distracting when scanning the logs for errors, so they were removed.

SUP-14417 Remove superfluous error logs for 4xx errors

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/endpoint/node/BinaryUploadHandlerImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingContentDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeWebRootConflictEndpointTest.java

Reproducible in the mesh-ui:
Create a new Schema "test"
with a field "id" type string and binary with name "binary"
set segment field to id
Create a new project "test" and link schema
Create a new node with schema "test" and fill id with "1" -> save
Create a new node and fill id with "1" again -> save -> ERROR because segment field already used
Edit first created node and upload a binary in the binary field -> save
Try again to create a new node with id "1" -> save -> WORKS
=> now you have two nodes with the same segment field

SUP-14472: Two nodes with same path/segment field if binary is filled

---

.gitignore
LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/event/EventBusLivenessManagerImpl.java

If the cluster manager reports unresponsive pod on an own instance name, the instance should be considered "broken" and liveness check should fail so a restart can be triggered from an external System(Kubernetes, monitoring).

SUP-14448: Mesh: LivenessCheck returns 200 even if EventbusCheck fails

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java

If the segment field name is empty, the segment info is treated as outdated and is subject to reset.

Reset segment info, if segment field is null

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/GraphQLOptions.java
bom/pom.xml
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-rest-client/src/main/java/com/gentics/mesh/rest/RestClientTest.java
verticles/graphql/pom.xml
verticles/graphql/src/main/java/com/gentics/mesh/graphql/GraphQLHandler.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/SchemaFilter.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/AbstractTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/FieldDefinitionProvider.java

Although GraphQL is called synchronously, we sometimes see worker threads, which are blocked forever while waiting for the CompletableFuture to complete. Therefore, this change introduces a timeout while waiting for the CompletableFuture to complete.
Also, the GraphQL Library has been updated to the most recent version (20.0).

Hotfix 1.8.x sup 14743

---

databases/orientdb/src/test/java/com/gentics/mesh/graphdb/orientdb/changelog/ChangelogSystemTest.java
test-common/src/main/java/com/gentics/mesh/test/docker/MeshContainer.java
test-common/src/main/resources/Dockerfile.local

Since recent OrientDB update the hard RAM limits have to be set for the cluster envs. The Java 8 environment is updated, since the old one is not anymore hosted.

Cluster test fixes

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/distributed/DistributionUtils.java
tests/tests-distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/RequestDelegatorRegexTest.java

Search endpoints should be treated read-only (and should therefore neither be forwarded to the master nor blocked due to topology change), but were not, because the patterns for checking were incorrect.

Add readonly patterns for search endpoints

---

LTS-CHANGELOG.adoc
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/endpoint/admin/consistency/check/GraphFieldContainerCheck.java
tests/context-orientdb/src/main/java/com/gentics/mesh/core/admin/ConsistencyCheckTest.java

If a NodeImpl has multiple INITIAL edges for the same language and branch, all edges but the first one can safely be deleted when doing a consistency repair.

Add check and repair for multiple INITIAL edges

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/MeshOptions.java
core/src/main/java/com/gentics/mesh/core/migration/AbstractMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/migration/impl/BranchMigrationImpl.java
core/src/main/java/com/gentics/mesh/core/migration/impl/MicronodeMigrationImpl.java
core/src/main/java/com/gentics/mesh/core/migration/impl/NodeMigrationImpl.java
core/src/main/java/com/gentics/mesh/core/verticle/job/JobWorkerVerticleImpl.java
distributed-coordinator/src/main/java/com/gentics/mesh/distributed/coordinator/proxy/ClusterEnabledRequestDelegatorImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/jobs/JobProcessor.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/JobProcessorImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/migration/MigrationAbortedException.java
mdm/common/src/main/java/com/gentics/mesh/core/migration/impl/MigrationStatusHandlerImpl.java

Execution of migration jobs has been made more robust: In cases, were the migration job is stopped unexpectedly (e.g. because the instance executing it was stopped, or is no longer the master in a cluster or the database turned read-only or write quorum is not reached), the execution will now automatically be triggered as soon as possible.

Make migration jobs more robust

---

tests/context-api/src/main/java/com/gentics/mesh/test/MeshCoreOptionChanger.java
tests/context-api/src/main/java/com/gentics/mesh/test/MeshOptionChanger.java
tests/context-api/src/main/java/com/gentics/mesh/test/MeshTestSetting.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/UploadNoParserTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/InitialAdminPasswordTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webroot/WebRootEndpointNoCacheTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/webrootfield/WebRootFieldEndpointNoCacheTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/ElasticSearchProviderTimeoutTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeBinaryDisabledSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/NodeSearchEndpointStrictModeTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/migration/BatchedNodeMigrationSearchTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/resilience/ElasticsearchEventBufferTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestHelper.java

Add an API for custom extension of Mesh Options for a particular test.

Extend test framework with custom options changer support

---

CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/PermissionCacheImpl.java
mdm/api/src/main/java/com/gentics/mesh/cache/PermissionCache.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLPermissionQueryTest.java
tests/tests-core/src/main/resources/graphql/childrenPerms

Provides an API for managing the distinct cache items.

API for permission cache fine tuning

---

CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/ContentDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingContentDao.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/ContentDaoWrapperImpl.java

Add method to check for uniqueness of webroot field values for a set of strings. Other persistence implementations might implement this more efficiently.

Add method to check for conflicting webroot fields for a set of values

---

CHANGELOG.adoc
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java

The OAuth plugin run triggers a log warning about missing role/group connection, which may not be true.

SUP-15553: Erratic logging upon OAUth plugins run

---

LTS-CHANGELOG.adoc
rest-client/src/main/java/com/gentics/mesh/rest/JWTAuthentication.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshRestOkHttpClientImpl.java
rest-client/src/main/java/com/gentics/mesh/rest/monitoring/impl/MonitoringOkHttpClientImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/client/MeshRestClientTokenTest.java

When doing a login, the returned login token will expire after some time (1 hour per default). If the login token is not refreshed,  all requests will be answered with 401 after expiration.
This change will now refresh the login token with the new one, which is sent as cookie in every response.

Refresh login token in MeshRestClient

---

LTS-CHANGELOG.adoc
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/AbstractTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/MicroschemaTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/NodeTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/SchemaTypeProvider.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/field/MicronodeFieldTypeProvider.java

If a microschema with no fields exists in Mesh, the GraphQL metadata request crashes with HTTP500.

SUP-15602: Fix the GraphQL metadata request for an empty (micro)schema.

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java

When running in the massive concurrent publishing process, it is possible to run into a race condition when some field containers are already processed while being referenced by the edge, 
throwing an NPE.

Hotfix sup 15750

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerTransformer.java
mdm/api/src/main/java/com/gentics/mesh/core/data/HibFieldContainer.java
mdm/common/src/main/java/com/gentics/mesh/core/data/node/field/RestUpdaters.java

Massive parallel publishing causes NPEs at the node reference fields.

SUP-15795: More potential NPEs at the node reference fields healed

---

bom/pom.xml
changelog/src/changelog/entries/2023/10/7577.SUP-15895.bugfix
verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/ListFilter.java

The used graphql-filter library was not thread-safe, which caused some internal errors (like You have redefined the type 'StringFilter' from being a 'GraphQLInputObjectType' to a 'GraphQLInputObjectType') when executing GraphQL requests.
The issue has been fixed in the graphql-filter library.

Hotfix 2.0.x sup 15895

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/auth/provider/MeshJWTAuthProvider.java

No need to log the failed auth with WARN level.

SUP-15263: Remove unnecessary token logging

---

LTS-CHANGELOG.adoc
api/src/main/java/com/gentics/mesh/etc/config/GraphQLOptions.java
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLSchemaCacheTest.java
verticles/graphql/src/main/java/com/gentics/mesh/cache/GraphQLSchemaCache.java
verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java

Without caching, the GraphQlSchema instances were created on every request. Creating the instances could be slow, if hundreds (or thousands) of schemas are assigned to the project.

Implement cache for GraphQlSchema instances

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cli/AbstractBootstrapInitializer.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingUserDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/core/user/UserTest.java

It is possible ATM to set an empty string as password, that should not be the case.

SUP-15674: Disallow empty or spaced password

---

LTS-CHANGELOG.adoc
mdm/api/src/main/java/com/gentics/mesh/core/data/HibNamedBaseElement.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/DaoGlobal.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/GroupDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/dao/UserDao.java
mdm/api/src/main/java/com/gentics/mesh/core/data/group/HibGroup.java
mdm/api/src/main/java/com/gentics/mesh/core/data/role/HibRole.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/GroupDaoWrapperImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/UserDaoWrapperImpl.java
rest-model/src/main/java/com/gentics/mesh/core/rest/event/AbstractElementMeshEventModel.java
rest-model/src/main/java/com/gentics/mesh/core/rest/event/group/GroupRoleAssignModel.java
rest-model/src/main/java/com/gentics/mesh/core/rest/event/group/GroupUserAssignModel.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/util/MappingHelper.java
tests/tests-core/src/main/java/com/gentics/mesh/auth/TokenMappingTest.java

Synchronization of users, groups and roles from AuthServicePlugin possibly handles multiple elements, in order to improve performance, the implementation is changed to support batch loading where possible.
Also parallel requests might handle the same entities, which can cause race conditions. In order to better handle such situations (without letting the request fail), the sync process is repeated once in case of an error.

Optimization of user/group/role sync

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/bulk/BulkOperator.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/bulk/BulkQueue.java
tests/tests-core/src/main/java/com/gentics/mesh/search/ElasticSearchProviderTimeoutTest.java
tests/tests-elasticsearch/src/main/java/com/gentics/mesh/search/verticle/bulk/BulkOperatorTest.java

There exists a possibility of DDoSing the Elasticsearch server, if a network glitch makes Mesh collecting unlimited ES requests, which are then pushed for the processing all at once.

SUP-16283: Make bulk request loader follow the limits in the edge cases

---

LTS-CHANGELOG.adoc
rest-client/src/main/java/com/gentics/mesh/rest/client/EventbusEvent.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/OkHttpWebsocket.java
tests/tests-core/src/main/java/com/gentics/mesh/core/eventbus/EventbusEndpointTest.java

Errors from Vert.x when creating an eventbus WebSocket where not handled which caused a NullPointerException during event creation. Typical errors like invalid event addresses are now handled, and multiple registrations of the same address no longer lead to errors.

SUP-16159 Improve WebSocket error handling

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/cache/ProjectBranchNameCacheImpl.java
core/src/main/java/com/gentics/mesh/cache/WebrootPathCacheImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/cache/ActionContextBranchCacheTest.java

A latest-assignment event has been missing in the branch name cache invalidation strategy.

Branch cache invalidation improved

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingContentDao.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeEndpointTest.java

When creating a new translation of a project's root node, the parent node uuid is not required, because the root node does not have a parent anyways.
Also the check for uniqueness of the segment field value has been fixed to treat empty string and null both as "not set".

Fix checks when creating a language variant of the project root node

---

common/src/main/java/com/gentics/mesh/verticle/AbstractJobVerticle.java
core/src/main/java/com/gentics/mesh/core/verticle/job/JobWorkerVerticleImpl.java
mdm/common/src/main/java/com/gentics/mesh/core/verticle/job/JobWorkerVerticle.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

resetting database during test execution
The tested database is reset between test executions. The JobWorkerVerticle (or any of its jobs) should not be running while this is done.

Stop JobWorkerVerticle and wait for currently running jobs before

---

LTS-CHANGELOG.adoc
elasticsearch/src/main/java/com/gentics/mesh/search/index/AbstractSearchHandler.java
tests/tests-core/src/main/java/com/gentics/mesh/search/permission/NodePermissionSearchTest.java

The ES requests currently disobey the ignorance of the permission checks for the admin users.

SUP-14117: Admin users should have full access to the data stored in ES

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/cache/impl/EventAwareCacheImpl.java
core/src/main/java/com/gentics/mesh/cache/AbstractNameCache.java
mdm/api/src/main/java/com/gentics/mesh/core/data/HibLanguage.java
mdm/api/src/main/java/com/gentics/mesh/core/data/branch/HibBranch.java
mdm/api/src/main/java/com/gentics/mesh/core/data/group/HibGroup.java
mdm/api/src/main/java/com/gentics/mesh/core/data/project/HibProject.java
mdm/api/src/main/java/com/gentics/mesh/core/data/schema/HibFieldSchemaElement.java
mdm/api/src/main/java/com/gentics/mesh/core/data/tag/HibTag.java
mdm/api/src/main/java/com/gentics/mesh/core/data/tagfamily/HibTagFamily.java
mdm/api/src/main/java/com/gentics/mesh/core/data/user/HibUser.java
mdm/common/src/main/java/com/gentics/mesh/core/db/TxEntityPersistenceManager.java

An update to cache API, allowing attaching/detaching/reattaching actions on an cacheable entity.

SUP-15608: TX API for (re)attaching entities. DB-aware cache.

---

LTS-CHANGELOG.adoc
services/jwt-auth/src/main/java/com/gentics/mesh/auth/oauth2/MeshOAuth2ServiceImpl.java
services/jwt-auth/src/main/java/com/gentics/mesh/auth/util/KeycloakUtils.java
tests/common/src/main/java/com/gentics/mesh/test/docker/KeycloakContainer.java

An ability to reformat the Keycloak request URL.

SUP-16105: Support for newer Keycloak versions

---

changelog/src/changelog/entries/2023/08/7532.GPU-942.enhancement
core/src/main/java/com/gentics/mesh/auth/MeshBasicAuthLoginHandler.java
core/src/main/java/com/gentics/mesh/core/endpoint/auth/AuthenticationEndpoint.java

The request GET /auth/login will now also accept Authentication: Bearer headers (containing an API Token) and do a login (generate and return a login token).

Add support for login with API token.

---

bom/pom.xml
changelog/src/changelog/entries/2024/03/7715.SUP-16448.bugfix
tests/tests-core/src/main/java/com/gentics/mesh/core/graphql/GraphQLEndpointTest.java
tests/tests-core/src/main/resources/graphql/nodes-query-by-uuids-common-filters

Common GraphQL filters (and, or, not) were missing from the API.

SUP-16448: Get back common filters

---

LTS-CHANGELOG.adoc
bom/pom.xml
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/ElasticsearchProcessVerticle.java
elasticsearch/src/main/java/com/gentics/mesh/search/verticle/IdleChecker.java
rest-client/src/main/java/com/gentics/mesh/rest/client/impl/MeshOkHttpRequestImpl.java
tests/tests-core/pom.xml
tests/tests-core/src/main/java/com/gentics/mesh/search/ElasticSearchProviderTimeoutTest.java

ES timeout tests were failing. Reimplemented + extended.

SUP-16917: Get back timeout tests

---

LTS-CHANGELOG.adoc
core/src/main/java/com/gentics/mesh/core/migration/AbstractMigrationHandler.java
core/src/main/java/com/gentics/mesh/core/migration/impl/MicronodeMigrationImpl.java
core/src/main/java/com/gentics/mesh/core/migration/impl/NodeMigrationImpl.java
mdm/api/src/main/java/com/gentics/mesh/core/data/HibFieldContainer.java
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingBranchDao.java
mdm/common/src/main/java/com/gentics/mesh/core/migration/impl/MigrationStatusHandlerImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/container/impl/AbstractGraphFieldContainerImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/container/impl/NodeGraphFieldContainerImpl.java
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/impl/GraphFieldTypes.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java

It should not be allowed to perform a (micro)node migration over two non-adjacent (micro)schema versions, since there is no way to determine and apply the correct set of changes.

SUP-17264: Don't jump over several schema versions during migration

---

LTS-CHANGELOG.adoc
mdm/orientdb-wrapper/src/main/java/com/gentics/mesh/core/data/dao/impl/NodeDaoWrapperImpl.java

A result set of an any intermediate GraphQL processing step may have duplications. One of those causes crashes.

SUP-17450: Duplicated data crash fix

---

api/src/main/java/com/gentics/mesh/etc/config/search/ComplianceMode.java
api/src/main/java/com/gentics/mesh/etc/config/search/ElasticSearchOptions.java
bom/pom.xml
changelog/src/changelog/entries/2024/07/7885.GPU-1625.enhancement
common-api/src/main/java/com/gentics/mesh/core/data/search/request/CreateDocumentRequest.java
common-api/src/main/java/com/gentics/mesh/core/data/search/request/DeleteDocumentRequest.java
common-api/src/main/java/com/gentics/mesh/core/data/search/request/UpdateDocumentRequest.java
doc/src/main/docs/elasticsearch.asciidoc
elasticsearch/src/main/java/com/gentics/mesh/search/impl/ElasticSearchProvider.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/AbstractMappingProvider.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/AbstractSearchHandler.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeContainerMappingProviderImpl.java
elasticsearch/src/main/java/com/gentics/mesh/search/index/node/NodeSearchHandler.java
tests/common/src/main/java/com/gentics/mesh/test/docker/ElasticsearchContainer.java
tests/context-api/src/main/java/com/gentics/mesh/test/ElasticsearchTestMode.java
tests/tests-core/src/main/java/com/gentics/mesh/core/schema/NodeMigrationEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/AbstractMultiESTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/CustomIndexSettingsTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/WaitSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/raw/NodeRawSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/raw/project/ProjectNodeRawSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/raw/project/ProjectTagFamilyRawSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/search/raw/project/ProjectTagRawSearchEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Make sure Mesh is compatible with Elasticsearch 8.x. New compliance mode ES_8 added. Documentation updated on how to create HTTPS certificates. Mapping and index operations updated to work with ES 8. Added ES 8 version to test container and changed tests to run with ES 6, ES 7 and ES 8.
* [X ] Added abstract that describes the change

GPU-1625: Elasticsearch 8.x compatibility

---

Jenkinsfile.split
bom/pom.xml
connectors/hsqldb/pom.xml
database-tests/common/pom.xml
pom.xml
test-scanner/pom.xml
tests/common/pom.xml
tests/common/src/main/java/com/gentics/mesh/maven/MavenUtilities.java
tests/pom.xml
tests/tests-core/src/test/plugins/pom.xml

GPU-1805: Scan image and dependency updates

---

LTS-CHANGELOG.adoc
mdm/common/src/main/java/com/gentics/mesh/core/data/dao/PersistingNodeDao.java
tests/tests-core/src/main/java/com/gentics/mesh/core/node/NodeLanguagesEndpointTest.java

The potential for node deletion misuse has been shrunk.

Hotfix 1.10.x sup 17755

---

bom/pom.xml
changelog/src/changelog/entries/2024/12/8096.SUP-17916.bugfix
core/pom.xml
core/src/main/resources/config/hazelcast.xml
doc/src/main/hugo/content/docs/clustering.asciidoc
mdm/hibernate-core/src/main/java/com/gentics/mesh/changelog/HibernateBootstrapInitializerImpl.java
mdm/hibernate-core/src/main/java/com/gentics/mesh/database/cluster/HibClusterManager.java
plugin-parent/pom.xml

Support for kubernetes autodiscovery is now built into hazelcast, so the plugin is not necessary (and is actually incompatible).

SUP 17916: Remove unnecessary dependency on kubernetes plugin for hazelcast

---

LTS-CHANGELOG.adoc
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/ImageCacheMigrationProcessor.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

the old structure.
Fix the image cache migration to delete all folders of the old structure
Accessing the binary image cache must not create directories of the old structure while searching cache files.
The migration of the old structure must delete the old directories even if they are empty or contain cache files which cannot be migrated because the binary no longer exists.

SUP 17176: Fix accessing files in the binary image cache to not create folders of

---

LTS-CHANGELOG.adoc
changelog/src/changelog/entries/2024/12/8095.SUP-17176.bugfix
common/src/main/java/com/gentics/mesh/core/image/spi/AbstractImageManipulator.java
mdm/common/src/main/java/com/gentics/mesh/core/jobs/ImageCacheMigrationProcessor.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java
tests/tests-core/src/main/java/com/gentics/mesh/test/context/MeshTestContext.java

Accessing the binary image cache must not create directories of the old structure while searching cache files.
The migration of the old structure must delete the old directories even if they are empty or contain cache files which cannot be migrated because the binary no longer exists.

SUP 17176: Fix accessing files in the binary image cache to not create folders of old structure

---

tests/tests-core/src/main/resources/graphql/filtering/nodes-string-field-native

Add a UT for a case when a GraphQL filter value can be parsed as UUID.

SUP-18069: Unit test filtering string field against UUID value

---

changelog/src/changelog/entries/2025/03/8182.SUP-18177.enhancement
core/src/main/java/com/gentics/mesh/core/endpoint/admin/AdminEndpoint.java
core/src/main/java/com/gentics/mesh/core/endpoint/admin/debuginfo/DebugInfoHandler.java
doc/src/main/hugo/content/docs/administration-guide.asciidoc
doc/src/main/hugo/content/docs/contributing.asciidoc

Fix reusing the docs from Mesh OSS in the EE builds. Add a docu for the backup/restore.

Fix the docu build

---

changelog/src/changelog/entries/2025/03/8207.SUP-18280.bugfix
mdm/api/src/main/java/com/gentics/mesh/core/data/node/field/HibBinaryField.java
rest-model/src/main/java/com/gentics/mesh/core/rest/node/field/impl/BinaryFieldImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldEndpointTest.java

Since the introduction of a virus checker, a new field on a binary payload prevents a changed data from being compared to the existing one, as the changed has postponed status by default, which is false for the cases where no virus check is set up. The check status is modified after the basic comparison.

Hotfix 2.1.x sup 18280

---

changelog/src/changelog/entries/2025/04/8250.SUP-18468.bugfix
mdm/hibernate-core/src/main/java/com/gentics/mesh/hibernate/data/domain/HibImageVariantImpl.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/binary/BinaryFieldVariantsTest.java

Comparison of floating point values for equality in MariaDB does not yield the expected results, so the comparison has been modified to abs(field - value) < 0.0000001

Fix floating point comparisons

---

changelog/src/changelog/entries/2025/04/8245.SUP-18399.bugfix
common/src/main/java/com/gentics/mesh/auth/provider/MeshJWTAuthProvider.java
core/src/main/java/com/gentics/mesh/auth/MeshBasicAuthLoginHandler.java

Missing occurrences of `HTTPOnly` flag on a token.

SUP-18399: More HTTPOnly flag occurrences

---

changelog/src/changelog/entries/2025/07/8331.SUP-18746.bugfix
mdm/hibernate-core/src/main/java/com/gentics/mesh/contentoperation/DynamicContentColumn.java
rest-model/src/main/java/com/gentics/mesh/util/DateUtils.java
tests/tests-core/src/main/java/com/gentics/mesh/core/field/date/DateFieldEndpointTest.java

As we already have the date parser, use it.

SUP-18746: Fix the parsing of both ISO-8601 variants
